// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Source: meshtastic/admin.proto

package pb

// AdminMessage_ConfigType defines config types for admin operations.
type AdminMessage_ConfigType int32

const (
	AdminMessage_DEVICE_CONFIG      AdminMessage_ConfigType = 0
	AdminMessage_POSITION_CONFIG    AdminMessage_ConfigType = 1
	AdminMessage_POWER_CONFIG       AdminMessage_ConfigType = 2
	AdminMessage_NETWORK_CONFIG     AdminMessage_ConfigType = 3
	AdminMessage_DISPLAY_CONFIG     AdminMessage_ConfigType = 4
	AdminMessage_LORA_CONFIG        AdminMessage_ConfigType = 5
	AdminMessage_BLUETOOTH_CONFIG   AdminMessage_ConfigType = 6
	AdminMessage_SECURITY_CONFIG    AdminMessage_ConfigType = 7
	AdminMessage_SESSIONKEY_CONFIG  AdminMessage_ConfigType = 8
	AdminMessage_DEVICE_UI_CONFIG   AdminMessage_ConfigType = 9
)

var AdminMessage_ConfigType_name = map[int32]string{
	0: "DEVICE_CONFIG",
	1: "POSITION_CONFIG",
	2: "POWER_CONFIG",
	3: "NETWORK_CONFIG",
	4: "DISPLAY_CONFIG",
	5: "LORA_CONFIG",
	6: "BLUETOOTH_CONFIG",
	7: "SECURITY_CONFIG",
	8: "SESSIONKEY_CONFIG",
	9: "DEVICE_UI_CONFIG",
}

func (x AdminMessage_ConfigType) String() string {
	if s, ok := AdminMessage_ConfigType_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// AdminMessage_ModuleConfigType defines module config types.
type AdminMessage_ModuleConfigType int32

const (
	AdminMessage_MQTT_CONFIG                 AdminMessage_ModuleConfigType = 0
	AdminMessage_SERIAL_CONFIG               AdminMessage_ModuleConfigType = 1
	AdminMessage_EXTNOTIF_CONFIG             AdminMessage_ModuleConfigType = 2
	AdminMessage_STOREFORWARD_CONFIG         AdminMessage_ModuleConfigType = 3
	AdminMessage_RANGETEST_CONFIG            AdminMessage_ModuleConfigType = 4
	AdminMessage_TELEMETRY_CONFIG            AdminMessage_ModuleConfigType = 5
	AdminMessage_CANNEDMSG_CONFIG            AdminMessage_ModuleConfigType = 6
	AdminMessage_AUDIO_CONFIG                AdminMessage_ModuleConfigType = 7
	AdminMessage_REMOTEHARDWARE_CONFIG       AdminMessage_ModuleConfigType = 8
	AdminMessage_NEIGHBORINFO_CONFIG         AdminMessage_ModuleConfigType = 9
	AdminMessage_AMBIENTLIGHTING_CONFIG      AdminMessage_ModuleConfigType = 10
	AdminMessage_DETECTIONSENSOR_CONFIG      AdminMessage_ModuleConfigType = 11
	AdminMessage_PAXCOUNTER_CONFIG           AdminMessage_ModuleConfigType = 12
)

var AdminMessage_ModuleConfigType_name = map[int32]string{
	0:  "MQTT_CONFIG",
	1:  "SERIAL_CONFIG",
	2:  "EXTNOTIF_CONFIG",
	3:  "STOREFORWARD_CONFIG",
	4:  "RANGETEST_CONFIG",
	5:  "TELEMETRY_CONFIG",
	6:  "CANNEDMSG_CONFIG",
	7:  "AUDIO_CONFIG",
	8:  "REMOTEHARDWARE_CONFIG",
	9:  "NEIGHBORINFO_CONFIG",
	10: "AMBIENTLIGHTING_CONFIG",
	11: "DETECTIONSENSOR_CONFIG",
	12: "PAXCOUNTER_CONFIG",
}

func (x AdminMessage_ModuleConfigType) String() string {
	if s, ok := AdminMessage_ModuleConfigType_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// HamParameters contains amateur radio license parameters.
type HamParameters struct {
	CallSign       string `protobuf:"bytes,1,opt,name=call_sign,json=callSign,proto3" json:"callSign,omitempty"`
	TxPower        int32  `protobuf:"varint,2,opt,name=tx_power,json=txPower,proto3" json:"txPower,omitempty"`
	Frequency      float32 `protobuf:"fixed32,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	ShortName      string `protobuf:"bytes,4,opt,name=short_name,json=shortName,proto3" json:"shortName,omitempty"`
}

func (h *HamParameters) Reset() { *h = HamParameters{} }
func (h *HamParameters) ProtoMessage() {}

// NodeRemoteHardwarePin represents a remote hardware pin on a specific node.
type NodeRemoteHardwarePin struct {
	NodeNum uint32             `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"nodeNum,omitempty"`
	Pin     *RemoteHardwarePin `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
}

func (n *NodeRemoteHardwarePin) Reset() { *n = NodeRemoteHardwarePin{} }
func (n *NodeRemoteHardwarePin) ProtoMessage() {}

// AdminMessage is the main admin message envelope.
type AdminMessage struct {
	// Session passkey for security (expires after 300 seconds)
	SessionPasskey []byte `protobuf:"bytes,101,opt,name=session_passkey,json=sessionPasskey,proto3" json:"sessionPasskey,omitempty"`

	// Types that are valid to be assigned to PayloadVariant:
	//	*AdminMessage_GetConfigRequest
	//	*AdminMessage_GetConfigResponse
	//	*AdminMessage_GetModuleConfigRequest
	//	*AdminMessage_GetModuleConfigResponse
	//	*AdminMessage_GetChannelRequest
	//	*AdminMessage_GetChannelResponse
	//	*AdminMessage_GetOwnerRequest
	//	*AdminMessage_GetOwnerResponse
	//	*AdminMessage_SetConfig
	//	*AdminMessage_SetModuleConfig
	//	*AdminMessage_SetChannel
	//	*AdminMessage_SetOwner
	//	*AdminMessage_BeginEditSettings
	//	*AdminMessage_CommitEditSettings
	//	*AdminMessage_RebootOtaSeconds
	//	*AdminMessage_RebootSeconds
	//	*AdminMessage_ShutdownSeconds
	//	*AdminMessage_FactoryReset
	//	*AdminMessage_NodedbReset
	//	*AdminMessage_SetHamMode
	//	*AdminMessage_GetNodeRemoteHardwarePinsRequest
	//	*AdminMessage_GetNodeRemoteHardwarePinsResponse
	//	*AdminMessage_EnterDfuModeRequest
	//	*AdminMessage_DeleteFileRequest
	//	*AdminMessage_SetFixedPosition
	//	*AdminMessage_RemoveFixedPosition
	//	*AdminMessage_SetTimeOnly
	PayloadVariant isAdminMessage_PayloadVariant
}

type isAdminMessage_PayloadVariant interface {
	isAdminMessage_PayloadVariant()
}

type AdminMessage_GetConfigRequest struct {
	GetConfigRequest AdminMessage_ConfigType
}

type AdminMessage_GetConfigResponse struct {
	GetConfigResponse *Config
}

type AdminMessage_GetModuleConfigRequest struct {
	GetModuleConfigRequest AdminMessage_ModuleConfigType
}

type AdminMessage_GetModuleConfigResponse struct {
	GetModuleConfigResponse *ModuleConfig
}

type AdminMessage_GetChannelRequest struct {
	GetChannelRequest uint32
}

type AdminMessage_GetChannelResponse struct {
	GetChannelResponse *Channel
}

type AdminMessage_GetOwnerRequest struct {
	GetOwnerRequest bool
}

type AdminMessage_GetOwnerResponse struct {
	GetOwnerResponse *User
}

type AdminMessage_SetConfig struct {
	SetConfig *Config
}

type AdminMessage_SetModuleConfig struct {
	SetModuleConfig *ModuleConfig
}

type AdminMessage_SetChannel struct {
	SetChannel *Channel
}

type AdminMessage_SetOwner struct {
	SetOwner *User
}

type AdminMessage_BeginEditSettings struct {
	BeginEditSettings bool
}

type AdminMessage_CommitEditSettings struct {
	CommitEditSettings bool
}

type AdminMessage_RebootOtaSeconds struct {
	RebootOtaSeconds int32
}

type AdminMessage_RebootSeconds struct {
	RebootSeconds int32
}

type AdminMessage_ShutdownSeconds struct {
	ShutdownSeconds int32
}

type AdminMessage_FactoryReset struct {
	FactoryReset int32
}

type AdminMessage_NodedbReset struct {
	NodedbReset int32
}

type AdminMessage_SetHamMode struct {
	SetHamMode *HamParameters
}

type AdminMessage_GetNodeRemoteHardwarePinsRequest struct {
	GetNodeRemoteHardwarePinsRequest bool
}

type AdminMessage_GetNodeRemoteHardwarePinsResponse struct {
	GetNodeRemoteHardwarePinsResponse *NodeRemoteHardwarePinsResponse
}

type AdminMessage_EnterDfuModeRequest struct {
	EnterDfuModeRequest bool
}

type AdminMessage_DeleteFileRequest struct {
	DeleteFileRequest string
}

type AdminMessage_SetFixedPosition struct {
	SetFixedPosition *Position
}

type AdminMessage_RemoveFixedPosition struct {
	RemoveFixedPosition bool
}

type AdminMessage_SetTimeOnly struct {
	SetTimeOnly uint32
}

func (*AdminMessage_GetConfigRequest) isAdminMessage_PayloadVariant()                   {}
func (*AdminMessage_GetConfigResponse) isAdminMessage_PayloadVariant()                  {}
func (*AdminMessage_GetModuleConfigRequest) isAdminMessage_PayloadVariant()             {}
func (*AdminMessage_GetModuleConfigResponse) isAdminMessage_PayloadVariant()            {}
func (*AdminMessage_GetChannelRequest) isAdminMessage_PayloadVariant()                  {}
func (*AdminMessage_GetChannelResponse) isAdminMessage_PayloadVariant()                 {}
func (*AdminMessage_GetOwnerRequest) isAdminMessage_PayloadVariant()                    {}
func (*AdminMessage_GetOwnerResponse) isAdminMessage_PayloadVariant()                   {}
func (*AdminMessage_SetConfig) isAdminMessage_PayloadVariant()                          {}
func (*AdminMessage_SetModuleConfig) isAdminMessage_PayloadVariant()                    {}
func (*AdminMessage_SetChannel) isAdminMessage_PayloadVariant()                         {}
func (*AdminMessage_SetOwner) isAdminMessage_PayloadVariant()                           {}
func (*AdminMessage_BeginEditSettings) isAdminMessage_PayloadVariant()                  {}
func (*AdminMessage_CommitEditSettings) isAdminMessage_PayloadVariant()                 {}
func (*AdminMessage_RebootOtaSeconds) isAdminMessage_PayloadVariant()                   {}
func (*AdminMessage_RebootSeconds) isAdminMessage_PayloadVariant()                      {}
func (*AdminMessage_ShutdownSeconds) isAdminMessage_PayloadVariant()                    {}
func (*AdminMessage_FactoryReset) isAdminMessage_PayloadVariant()                       {}
func (*AdminMessage_NodedbReset) isAdminMessage_PayloadVariant()                        {}
func (*AdminMessage_SetHamMode) isAdminMessage_PayloadVariant()                         {}
func (*AdminMessage_GetNodeRemoteHardwarePinsRequest) isAdminMessage_PayloadVariant()   {}
func (*AdminMessage_GetNodeRemoteHardwarePinsResponse) isAdminMessage_PayloadVariant()  {}
func (*AdminMessage_EnterDfuModeRequest) isAdminMessage_PayloadVariant()                {}
func (*AdminMessage_DeleteFileRequest) isAdminMessage_PayloadVariant()                  {}
func (*AdminMessage_SetFixedPosition) isAdminMessage_PayloadVariant()                   {}
func (*AdminMessage_RemoveFixedPosition) isAdminMessage_PayloadVariant()                {}
func (*AdminMessage_SetTimeOnly) isAdminMessage_PayloadVariant()                        {}

// Getter methods

func (a *AdminMessage) GetGetConfigRequest() AdminMessage_ConfigType {
	if x, ok := a.PayloadVariant.(*AdminMessage_GetConfigRequest); ok {
		return x.GetConfigRequest
	}
	return AdminMessage_DEVICE_CONFIG
}

func (a *AdminMessage) GetGetConfigResponse() *Config {
	if x, ok := a.PayloadVariant.(*AdminMessage_GetConfigResponse); ok {
		return x.GetConfigResponse
	}
	return nil
}

func (a *AdminMessage) GetGetModuleConfigRequest() AdminMessage_ModuleConfigType {
	if x, ok := a.PayloadVariant.(*AdminMessage_GetModuleConfigRequest); ok {
		return x.GetModuleConfigRequest
	}
	return AdminMessage_MQTT_CONFIG
}

func (a *AdminMessage) GetGetModuleConfigResponse() *ModuleConfig {
	if x, ok := a.PayloadVariant.(*AdminMessage_GetModuleConfigResponse); ok {
		return x.GetModuleConfigResponse
	}
	return nil
}

func (a *AdminMessage) GetGetChannelRequest() uint32 {
	if x, ok := a.PayloadVariant.(*AdminMessage_GetChannelRequest); ok {
		return x.GetChannelRequest
	}
	return 0
}

func (a *AdminMessage) GetGetChannelResponse() *Channel {
	if x, ok := a.PayloadVariant.(*AdminMessage_GetChannelResponse); ok {
		return x.GetChannelResponse
	}
	return nil
}

func (a *AdminMessage) GetSetConfig() *Config {
	if x, ok := a.PayloadVariant.(*AdminMessage_SetConfig); ok {
		return x.SetConfig
	}
	return nil
}

func (a *AdminMessage) GetSetModuleConfig() *ModuleConfig {
	if x, ok := a.PayloadVariant.(*AdminMessage_SetModuleConfig); ok {
		return x.SetModuleConfig
	}
	return nil
}

func (a *AdminMessage) GetSetChannel() *Channel {
	if x, ok := a.PayloadVariant.(*AdminMessage_SetChannel); ok {
		return x.SetChannel
	}
	return nil
}

func (a *AdminMessage) GetSetOwner() *User {
	if x, ok := a.PayloadVariant.(*AdminMessage_SetOwner); ok {
		return x.SetOwner
	}
	return nil
}

func (a *AdminMessage) GetRebootSeconds() int32 {
	if x, ok := a.PayloadVariant.(*AdminMessage_RebootSeconds); ok {
		return x.RebootSeconds
	}
	return 0
}

func (a *AdminMessage) GetShutdownSeconds() int32 {
	if x, ok := a.PayloadVariant.(*AdminMessage_ShutdownSeconds); ok {
		return x.ShutdownSeconds
	}
	return 0
}

func (a *AdminMessage) GetSetHamMode() *HamParameters {
	if x, ok := a.PayloadVariant.(*AdminMessage_SetHamMode); ok {
		return x.SetHamMode
	}
	return nil
}

func (a *AdminMessage) GetSetFixedPosition() *Position {
	if x, ok := a.PayloadVariant.(*AdminMessage_SetFixedPosition); ok {
		return x.SetFixedPosition
	}
	return nil
}

func (a *AdminMessage) Reset() { *a = AdminMessage{} }
func (a *AdminMessage) ProtoMessage() {}

// NodeRemoteHardwarePinsResponse contains the response for remote hardware pins request.
type NodeRemoteHardwarePinsResponse struct {
	NodeRemoteHardwarePins []*NodeRemoteHardwarePin `protobuf:"bytes,1,rep,name=node_remote_hardware_pins,json=nodeRemoteHardwarePins,proto3" json:"nodeRemoteHardwarePins,omitempty"`
}

func (n *NodeRemoteHardwarePinsResponse) Reset() { *n = NodeRemoteHardwarePinsResponse{} }
func (n *NodeRemoteHardwarePinsResponse) ProtoMessage() {}
