// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Source: meshtastic/channel.proto

package pb

// Channel_Role defines the role of a channel.
type Channel_Role int32

const (
	Channel_DISABLED  Channel_Role = 0
	Channel_PRIMARY   Channel_Role = 1
	Channel_SECONDARY Channel_Role = 2
)

var Channel_Role_name = map[int32]string{
	0: "DISABLED",
	1: "PRIMARY",
	2: "SECONDARY",
}

func (x Channel_Role) String() string {
	if s, ok := Channel_Role_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// ChannelSettings contains channel configuration.
type ChannelSettings struct {
	ChannelNum      uint32          `protobuf:"varint,1,opt,name=channel_num,json=channelNum,proto3" json:"channelNum,omitempty"`
	Psk             []byte          `protobuf:"bytes,2,opt,name=psk,proto3" json:"psk,omitempty"`
	Name            string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id              uint32          `protobuf:"fixed32,4,opt,name=id,proto3" json:"id,omitempty"`
	UplinkEnabled   bool            `protobuf:"varint,5,opt,name=uplink_enabled,json=uplinkEnabled,proto3" json:"uplinkEnabled,omitempty"`
	DownlinkEnabled bool            `protobuf:"varint,6,opt,name=downlink_enabled,json=downlinkEnabled,proto3" json:"downlinkEnabled,omitempty"`
	ModuleSettings  *ModuleSettings `protobuf:"bytes,7,opt,name=module_settings,json=moduleSettings,proto3" json:"moduleSettings,omitempty"`
}

func (c *ChannelSettings) Reset() { *c = ChannelSettings{} }
func (c *ChannelSettings) ProtoMessage() {}

// ModuleSettings contains per-channel module settings.
type ModuleSettings struct {
	PositionPrecision uint32 `protobuf:"varint,1,opt,name=position_precision,json=positionPrecision,proto3" json:"positionPrecision,omitempty"`
	IsClientMuted     bool   `protobuf:"varint,2,opt,name=is_client_muted,json=isClientMuted,proto3" json:"isClientMuted,omitempty"`
}

func (m *ModuleSettings) Reset() { *m = ModuleSettings{} }
func (m *ModuleSettings) ProtoMessage() {}

// Channel represents a mesh channel.
type Channel struct {
	Index    uint32           `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Settings *ChannelSettings `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	Role     uint32           `protobuf:"varint,3,opt,name=role,proto3,enum=meshtastic.Channel_Role" json:"role,omitempty"`
}

func (c *Channel) Reset() { *c = Channel{} }
func (c *Channel) ProtoMessage() {}

// ChannelSet is a compact representation of multiple channels.
type ChannelSet struct {
	Settings   []*ChannelSettings    `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	LoraConfig *Config_LoRaConfig    `protobuf:"bytes,2,opt,name=lora_config,json=loraConfig,proto3" json:"loraConfig,omitempty"`
}

func (c *ChannelSet) Reset() { *c = ChannelSet{} }
func (c *ChannelSet) ProtoMessage() {}
