// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Codec utilities for Meshtastic protobuf messages.

package pb

import (
	"encoding/binary"
	"errors"
	"math"
)

// Common errors
var (
	ErrBufferTooSmall = errors.New("buffer too small")
	ErrInvalidData    = errors.New("invalid protobuf data")
	ErrUnknownField   = errors.New("unknown field number")
)

// Wire types for protobuf encoding
const (
	WireVarint     = 0
	WireFixed64    = 1
	WireBytes      = 2
	WireStartGroup = 3
	WireEndGroup   = 4
	WireFixed32    = 5
)

// EncodeVarint encodes a uint64 as a varint.
func EncodeVarint(buf []byte, v uint64) int {
	i := 0
	for v >= 0x80 {
		buf[i] = byte(v) | 0x80
		v >>= 7
		i++
	}
	buf[i] = byte(v)
	return i + 1
}

// DecodeVarint decodes a varint from the buffer.
func DecodeVarint(buf []byte) (uint64, int) {
	var v uint64
	for i, b := range buf {
		if i >= 10 {
			return 0, 0 // overflow
		}
		v |= uint64(b&0x7f) << (7 * i)
		if b < 0x80 {
			return v, i + 1
		}
	}
	return 0, 0
}

// EncodeZigZag encodes a signed int64 using ZigZag encoding.
func EncodeZigZag(v int64) uint64 {
	return uint64((v << 1) ^ (v >> 63))
}

// DecodeZigZag decodes a ZigZag encoded value.
func DecodeZigZag(v uint64) int64 {
	return int64((v >> 1) ^ -(v & 1))
}

// EncodeTag encodes a field tag.
func EncodeTag(field uint32, wireType int) uint64 {
	return uint64(field)<<3 | uint64(wireType)
}

// DecodeTag decodes a field tag.
func DecodeTag(tag uint64) (field uint32, wireType int) {
	return uint32(tag >> 3), int(tag & 0x7)
}

// MarshalMeshPacket encodes a MeshPacket to protobuf wire format.
func MarshalMeshPacket(m *MeshPacket) ([]byte, error) {
	if m == nil {
		return nil, nil
	}

	// Estimate buffer size
	buf := make([]byte, 0, 256)
	tmp := make([]byte, 10)

	// Field 1: from (fixed32)
	if m.From != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, m.From)
		buf = append(buf, b...)
	}

	// Field 2: to (fixed32)
	if m.To != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, m.To)
		buf = append(buf, b...)
	}

	// Field 3: channel (varint)
	if m.Channel != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(m.Channel))
		buf = append(buf, tmp[:n]...)
	}

	// Field 4: decoded (Data message) or Field 5: encrypted (bytes)
	switch v := m.PayloadVariant.(type) {
	case *MeshPacket_Decoded:
		if v.Decoded != nil {
			data, err := MarshalData(v.Decoded)
			if err != nil {
				return nil, err
			}
			n := EncodeVarint(tmp, EncodeTag(4, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}
	case *MeshPacket_Encrypted:
		if len(v.Encrypted) > 0 {
			n := EncodeVarint(tmp, EncodeTag(5, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(v.Encrypted)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, v.Encrypted...)
		}
	}

	// Field 6: id (fixed32)
	if m.Id != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, m.Id)
		buf = append(buf, b...)
	}

	// Field 7: rx_time (fixed32)
	if m.RxTime != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, m.RxTime)
		buf = append(buf, b...)
	}

	// Field 8: rx_snr (float as fixed32)
	if m.RxSnr != 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, math.Float32bits(m.RxSnr))
		buf = append(buf, b...)
	}

	// Field 9: hop_limit (varint)
	if m.HopLimit != 0 {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(m.HopLimit))
		buf = append(buf, tmp[:n]...)
	}

	// Field 10: want_ack (bool as varint)
	if m.WantAck {
		n := EncodeVarint(tmp, EncodeTag(10, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 11: priority (varint)
	if m.Priority != 0 {
		n := EncodeVarint(tmp, EncodeTag(11, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(m.Priority))
		buf = append(buf, tmp[:n]...)
	}

	// Field 12: rx_rssi (varint)
	if m.RxRssi != 0 {
		n := EncodeVarint(tmp, EncodeTag(12, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(int32(m.RxRssi)))
		buf = append(buf, tmp[:n]...)
	}

	// Field 15: hop_start (varint)
	if m.HopStart != 0 {
		n := EncodeVarint(tmp, EncodeTag(15, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(m.HopStart))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// UnmarshalMeshPacket decodes a MeshPacket from protobuf wire format.
func UnmarshalMeshPacket(buf []byte) (*MeshPacket, error) {
	m := &MeshPacket{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // from
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			m.From = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 2: // to
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			m.To = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 3: // channel
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.Channel = uint32(v)
			offset += n

		case 4: // decoded
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			data, err := UnmarshalData(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			m.PayloadVariant = &MeshPacket_Decoded{Decoded: data}
			offset += int(length)

		case 5: // encrypted
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			encrypted := make([]byte, length)
			copy(encrypted, buf[offset:offset+int(length)])
			m.PayloadVariant = &MeshPacket_Encrypted{Encrypted: encrypted}
			offset += int(length)

		case 6: // id
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			m.Id = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 7: // rx_time
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			m.RxTime = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 8: // rx_snr
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			m.RxSnr = math.Float32frombits(binary.LittleEndian.Uint32(buf[offset:]))
			offset += 4

		case 9: // hop_limit
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.HopLimit = uint32(v)
			offset += n

		case 10: // want_ack
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.WantAck = v != 0
			offset += n

		case 11: // priority
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.Priority = MeshPacket_Priority(v)
			offset += n

		case 12: // rx_rssi
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.RxRssi = int32(v)
			offset += n

		case 13: // delayed
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.Delayed = uint32(v)
			offset += n

		case 14: // via_mqtt
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.ViaMqtt = v != 0
			offset += n

		case 15: // hop_start
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			m.HopStart = uint32(v)
			offset += n

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return m, nil
}

// MarshalData encodes a Data message to protobuf wire format.
func MarshalData(d *Data) ([]byte, error) {
	if d == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: portnum (varint)
	if d.Portnum != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(d.Portnum))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: payload (bytes)
	if len(d.Payload) > 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(d.Payload)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, d.Payload...)
	}

	// Field 3: want_response (bool)
	if d.WantResponse {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 4: dest (fixed32)
	if d.Dest != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, d.Dest)
		buf = append(buf, b...)
	}

	// Field 5: source (fixed32)
	if d.Source != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, d.Source)
		buf = append(buf, b...)
	}

	// Field 6: request_id (fixed32)
	if d.RequestId != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, d.RequestId)
		buf = append(buf, b...)
	}

	// Field 7: reply_id (fixed32)
	if d.ReplyId != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, d.ReplyId)
		buf = append(buf, b...)
	}

	// Field 8: emoji (fixed32)
	if d.Emoji != 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, d.Emoji)
		buf = append(buf, b...)
	}

	return buf, nil
}

// UnmarshalData decodes a Data message from protobuf wire format.
func UnmarshalData(buf []byte) (*Data, error) {
	d := &Data{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // portnum
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			d.Portnum = PortNum(v)
			offset += n

		case 2: // payload
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			d.Payload = make([]byte, length)
			copy(d.Payload, buf[offset:offset+int(length)])
			offset += int(length)

		case 3: // want_response
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			d.WantResponse = v != 0
			offset += n

		case 4: // dest
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			d.Dest = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 5: // source
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			d.Source = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 6: // request_id
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			d.RequestId = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 7: // reply_id
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			d.ReplyId = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 8: // emoji
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			d.Emoji = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return d, nil
}

// MarshalPosition encodes a Position message to protobuf wire format.
func MarshalPosition(p *Position) ([]byte, error) {
	if p == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: latitude_i (sfixed32)
	if p.LatitudeI != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, uint32(p.LatitudeI))
		buf = append(buf, b...)
	}

	// Field 2: longitude_i (sfixed32)
	if p.LongitudeI != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, uint32(p.LongitudeI))
		buf = append(buf, b...)
	}

	// Field 3: altitude (int32 varint)
	if p.Altitude != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(p.Altitude))
		buf = append(buf, tmp[:n]...)
	}

	// Field 4: time (fixed32)
	if p.Time != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, p.Time)
		buf = append(buf, b...)
	}

	return buf, nil
}

// UnmarshalPosition decodes a Position message from protobuf wire format.
func UnmarshalPosition(buf []byte) (*Position, error) {
	p := &Position{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // latitude_i
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			p.LatitudeI = int32(binary.LittleEndian.Uint32(buf[offset:]))
			offset += 4

		case 2: // longitude_i
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			p.LongitudeI = int32(binary.LittleEndian.Uint32(buf[offset:]))
			offset += 4

		case 3: // altitude
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			p.Altitude = int32(v)
			offset += n

		case 4: // time
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			p.Time = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return p, nil
}

// MarshalUser encodes a User message to protobuf wire format.
func MarshalUser(u *User) ([]byte, error) {
	if u == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: id (string)
	if u.Id != "" {
		n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(u.Id)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(u.Id)...)
	}

	// Field 2: long_name (string)
	if u.LongName != "" {
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(u.LongName)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(u.LongName)...)
	}

	// Field 3: short_name (string)
	if u.ShortName != "" {
		n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(u.ShortName)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(u.ShortName)...)
	}

	// Field 4: macaddr (bytes)
	if len(u.Macaddr) > 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(u.Macaddr)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, u.Macaddr...)
	}

	// Field 5: hw_model (enum as varint)
	if u.HwModel != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(u.HwModel))
		buf = append(buf, tmp[:n]...)
	}

	// Field 6: is_licensed (bool)
	if u.IsLicensed {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 7: role (varint)
	if u.Role != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(u.Role))
		buf = append(buf, tmp[:n]...)
	}

	// Field 8: public_key (bytes)
	if len(u.PublicKey) > 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(u.PublicKey)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, u.PublicKey...)
	}

	return buf, nil
}

// UnmarshalUser decodes a User message from protobuf wire format.
func UnmarshalUser(buf []byte) (*User, error) {
	u := &User{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // id
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			u.Id = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 2: // long_name
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			u.LongName = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 3: // short_name
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			u.ShortName = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 4: // macaddr
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			u.Macaddr = make([]byte, length)
			copy(u.Macaddr, buf[offset:offset+int(length)])
			offset += int(length)

		case 5: // hw_model
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			u.HwModel = HardwareModel(v)
			offset += n

		case 6: // is_licensed
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			u.IsLicensed = v != 0
			offset += n

		case 7: // role
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			u.Role = uint32(v)
			offset += n

		case 8: // public_key
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			u.PublicKey = make([]byte, length)
			copy(u.PublicKey, buf[offset:offset+int(length)])
			offset += int(length)

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return u, nil
}

// skipField skips over a field in the protobuf buffer.
func skipField(buf []byte, offset int, wireType int) int {
	switch wireType {
	case WireVarint:
		for offset < len(buf) {
			if buf[offset]&0x80 == 0 {
				return offset + 1
			}
			offset++
		}
		return -1

	case WireFixed64:
		if offset+8 > len(buf) {
			return -1
		}
		return offset + 8

	case WireBytes:
		length, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return -1
		}
		offset += n
		if offset+int(length) > len(buf) {
			return -1
		}
		return offset + int(length)

	case WireFixed32:
		if offset+4 > len(buf) {
			return -1
		}
		return offset + 4

	default:
		return -1
	}
}

// MarshalToRadio encodes a ToRadio message to protobuf wire format.
func MarshalToRadio(t *ToRadio) ([]byte, error) {
	if t == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 256)
	tmp := make([]byte, 10)

	switch v := t.PayloadVariant.(type) {
	case *ToRadio_Packet:
		if v.Packet != nil {
			data, err := MarshalMeshPacket(v.Packet)
			if err != nil {
				return nil, err
			}
			n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ToRadio_WantConfigId:
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(v.WantConfigId))
		buf = append(buf, tmp[:n]...)

	case *ToRadio_Disconnect:
		if v.Disconnect {
			n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, 1)
		}

	case *ToRadio_Heartbeat:
		// Heartbeat is an empty message
		n := EncodeVarint(tmp, EncodeTag(6, WireBytes))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 0) // Empty message
	}

	return buf, nil
}

// UnmarshalFromRadio decodes a FromRadio message from protobuf wire format.
func UnmarshalFromRadio(buf []byte) (*FromRadio, error) {
	f := &FromRadio{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // id
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			f.Id = uint32(v)
			offset += n

		case 2: // packet
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			packet, err := UnmarshalMeshPacket(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			f.PayloadVariant = &FromRadio_Packet{Packet: packet}
			offset += int(length)

		case 3: // my_info
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			// Parse MyNodeInfo
			myInfo := &MyNodeInfo{}
			infoOffset := offset
			infoEnd := offset + int(length)
			for infoOffset < infoEnd {
				infoTag, in := DecodeVarint(buf[infoOffset:])
				if in == 0 {
					break
				}
				infoOffset += in
				infoField, _ := DecodeTag(infoTag)
				switch infoField {
				case 1: // my_node_num
					v, vn := DecodeVarint(buf[infoOffset:])
					if vn == 0 {
						break
					}
					myInfo.MyNodeNum = uint32(v)
					infoOffset += vn
				default:
					infoOffset = skipField(buf, infoOffset, int(infoTag&0x7))
					if infoOffset < 0 {
						break
					}
				}
			}
			f.PayloadVariant = &FromRadio_MyInfo{MyInfo: myInfo}
			offset += int(length)

		case 4: // node_info
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			nodeInfo, err := UnmarshalNodeInfo(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			f.PayloadVariant = &FromRadio_NodeInfo{NodeInfo: nodeInfo}
			offset += int(length)

		case 5: // config
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			config, err := UnmarshalConfig(buf[offset : offset+int(length)])
			if err == nil && config != nil {
				f.PayloadVariant = &FromRadio_Config{Config: config}
			}
			offset += int(length)

		case 6: // log_record - skip for now
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}

		case 7: // config_complete_id
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			f.PayloadVariant = &FromRadio_ConfigCompleteId{ConfigCompleteId: uint32(v)}
			offset += n

		case 8: // rebooted
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			f.PayloadVariant = &FromRadio_Rebooted{Rebooted: v != 0}
			offset += n

		case 9: // module_config - skip for now
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			offset += int(length)

		case 10: // channel
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			channel, err := UnmarshalChannel(buf[offset : offset+int(length)])
			if err == nil && channel != nil {
				f.PayloadVariant = &FromRadio_Channel{Channel: channel}
			}
			offset += int(length)

		case 11: // queued_status - skip for now
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}

		case 13: // metadata
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			metadata, err := UnmarshalDeviceMetadata(buf[offset : offset+int(length)])
			if err == nil && metadata != nil {
				f.PayloadVariant = &FromRadio_Metadata{Metadata: metadata}
			}
			offset += int(length)

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return f, nil
}

// UnmarshalNodeInfo decodes a NodeInfo message from protobuf wire format.
func UnmarshalNodeInfo(buf []byte) (*NodeInfo, error) {
	n := &NodeInfo{}
	offset := 0

	for offset < len(buf) {
		tag, tn := DecodeVarint(buf[offset:])
		if tn == 0 {
			return nil, ErrInvalidData
		}
		offset += tn

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // num
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			n.Num = uint32(v)
			offset += vn

		case 2: // user
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			user, err := UnmarshalUser(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			n.User = user
			offset += int(length)

		case 3: // position
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			pos, err := UnmarshalPosition(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			n.Position = pos
			offset += int(length)

		case 4: // snr
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			n.Snr = math.Float32frombits(binary.LittleEndian.Uint32(buf[offset:]))
			offset += 4

		case 5: // last_heard
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			n.LastHeard = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 7: // channel
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			n.Channel = uint32(v)
			offset += vn

		case 8: // via_mqtt
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			n.ViaMqtt = v != 0
			offset += vn

		case 9: // hops
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			n.Hops = uint32(v)
			offset += vn

		case 10: // is_favorite
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			n.IsFavorite = v != 0
			offset += vn

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return n, nil
}

// UnmarshalChannel decodes a Channel message from protobuf wire format.
func UnmarshalChannel(buf []byte) (*Channel, error) {
	c := &Channel{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // index
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			c.Index = uint32(v)
			offset += vn

		case 2: // settings
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			settings, err := UnmarshalChannelSettings(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			c.Settings = settings
			offset += int(length)

		case 3: // role
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			c.Role = Channel_Role(v)
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return c, nil
}

// UnmarshalChannelSettings decodes ChannelSettings from protobuf wire format.
func UnmarshalChannelSettings(buf []byte) (*ChannelSettings, error) {
	cs := &ChannelSettings{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // channel_num
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			cs.ChannelNum = uint32(v)
			offset += vn

		case 2: // psk
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			cs.Psk = make([]byte, length)
			copy(cs.Psk, buf[offset:offset+int(length)])
			offset += int(length)

		case 3: // name
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			cs.Name = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 4: // id
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			cs.Id = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 5: // uplink_enabled
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			cs.UplinkEnabled = v != 0
			offset += vn

		case 6: // downlink_enabled
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			cs.DownlinkEnabled = v != 0
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return cs, nil
}

// UnmarshalConfig decodes a Config message from protobuf wire format.
func UnmarshalConfig(buf []byte) (*Config, error) {
	c := &Config{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // device
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			device, err := UnmarshalDeviceConfig(buf[offset : offset+int(length)])
			if err == nil {
				c.PayloadVariant = &Config_Device{Device: device}
			}
			offset += int(length)

		case 2: // position
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			pos, err := UnmarshalPositionConfig(buf[offset : offset+int(length)])
			if err == nil {
				c.PayloadVariant = &Config_Position{Position: pos}
			}
			offset += int(length)

		case 3: // power
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			offset += int(length)

		case 4: // network
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			offset += int(length)

		case 5: // display
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			offset += int(length)

		case 6: // lora
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			lora, err := UnmarshalLoRaConfig(buf[offset : offset+int(length)])
			if err == nil {
				c.PayloadVariant = &Config_Lora{Lora: lora}
			}
			offset += int(length)

		case 7: // bluetooth
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			offset += int(length)

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return c, nil
}

// UnmarshalDeviceConfig decodes a DeviceConfig from protobuf wire format.
func UnmarshalDeviceConfig(buf []byte) (*Config_DeviceConfig, error) {
	dc := &Config_DeviceConfig{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // role
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dc.Role = Config_DeviceConfig_Role(v)
			offset += vn

		case 2: // serial_enabled
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dc.SerialEnabled = v != 0
			offset += vn

		case 3: // debug_log_enabled
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dc.DebugLogEnabled = v != 0
			offset += vn

		case 7: // node_info_broadcast_secs
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dc.NodeInfoBroadcastSecs = uint32(v)
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return dc, nil
}

// UnmarshalPositionConfig decodes a PositionConfig from protobuf wire format.
func UnmarshalPositionConfig(buf []byte) (*Config_PositionConfig, error) {
	pc := &Config_PositionConfig{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // position_broadcast_secs
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			pc.PositionBroadcastSecs = uint32(v)
			offset += vn

		case 3: // fixed_position
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			pc.FixedPosition = v != 0
			offset += vn

		case 4: // gps_enabled
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			pc.GpsEnabled = v != 0
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return pc, nil
}

// UnmarshalLoRaConfig decodes a LoRaConfig from protobuf wire format.
func UnmarshalLoRaConfig(buf []byte) (*Config_LoRaConfig, error) {
	lc := &Config_LoRaConfig{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // use_preset
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.UsePreset = v != 0
			offset += vn

		case 2: // modem_preset
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.ModemPreset = Config_LoRaConfig_ModemPreset(v)
			offset += vn

		case 7: // region
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.Region = Config_LoRaConfig_RegionCode(v)
			offset += vn

		case 8: // hop_limit
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.HopLimit = uint32(v)
			offset += vn

		case 9: // tx_enabled
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.TxEnabled = v != 0
			offset += vn

		case 10: // tx_power
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.TxPower = int32(v)
			offset += vn

		case 11: // channel_num
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			lc.ChannelNum = uint32(v)
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return lc, nil
}

// UnmarshalDeviceMetadata decodes a DeviceMetadata from protobuf wire format.
func UnmarshalDeviceMetadata(buf []byte) (*DeviceMetadata, error) {
	dm := &DeviceMetadata{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // firmware_version
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				break
			}
			offset += ln
			if offset+int(length) > len(buf) {
				break
			}
			dm.FirmwareVersion = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 4: // has_wifi
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dm.HasWifi = v != 0
			offset += vn

		case 5: // has_bluetooth
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dm.HasBluetooth = v != 0
			offset += vn

		case 6: // has_ethernet
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dm.HasEthernet = v != 0
			offset += vn

		case 9: // hw_model
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			dm.HwModel = HardwareModel(v)
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return dm, nil
}

// MarshalChannel encodes a Channel message to protobuf wire format.
func MarshalChannel(c *Channel) ([]byte, error) {
	if c == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: index (varint)
	if c.Index != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(c.Index))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: settings (bytes)
	if c.Settings != nil {
		settingsData, err := MarshalChannelSettings(c.Settings)
		if err != nil {
			return nil, err
		}
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(settingsData)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, settingsData...)
	}

	// Field 3: role (varint)
	if c.Role != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(c.Role))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalChannelSettings encodes ChannelSettings to protobuf wire format.
func MarshalChannelSettings(cs *ChannelSettings) ([]byte, error) {
	if cs == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	// Field 1: channel_num (varint)
	if cs.ChannelNum != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(cs.ChannelNum))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: psk (bytes)
	if len(cs.Psk) > 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(cs.Psk)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, cs.Psk...)
	}

	// Field 3: name (string)
	if cs.Name != "" {
		n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(cs.Name)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(cs.Name)...)
	}

	// Field 4: id (fixed32)
	if cs.Id != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, cs.Id)
		buf = append(buf, b...)
	}

	// Field 5: uplink_enabled (bool)
	if cs.UplinkEnabled {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 6: downlink_enabled (bool)
	if cs.DownlinkEnabled {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalAdminMessage encodes an AdminMessage to protobuf wire format.
func MarshalAdminMessage(a *AdminMessage) ([]byte, error) {
	if a == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 256)
	tmp := make([]byte, 10)

	switch v := a.PayloadVariant.(type) {
	case *AdminMessage_SetConfig:
		if v.SetConfig != nil {
			configData, err := MarshalConfig(v.SetConfig)
			if err != nil {
				return nil, err
			}
			// Field 33: set_config
			n := EncodeVarint(tmp, EncodeTag(33, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(configData)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, configData...)
		}

	case *AdminMessage_SetModuleConfig:
		if v.SetModuleConfig != nil {
			moduleData, err := MarshalModuleConfig(v.SetModuleConfig)
			if err != nil {
				return nil, err
			}
			// Field 35: set_module_config
			n := EncodeVarint(tmp, EncodeTag(35, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(moduleData)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, moduleData...)
		}

	case *AdminMessage_SetChannel:
		if v.SetChannel != nil {
			channelData, err := MarshalChannel(v.SetChannel)
			if err != nil {
				return nil, err
			}
			// Field 34: set_channel
			n := EncodeVarint(tmp, EncodeTag(34, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(channelData)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, channelData...)
		}

	case *AdminMessage_BeginEditSettings:
		if v.BeginEditSettings {
			// Field 64: begin_edit_settings (bool)
			n := EncodeVarint(tmp, EncodeTag(64, WireVarint))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, 1)
		}

	case *AdminMessage_CommitEditSettings:
		if v.CommitEditSettings {
			// Field 65: commit_edit_settings (bool)
			n := EncodeVarint(tmp, EncodeTag(65, WireVarint))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, 1)
		}

	case *AdminMessage_RebootSeconds:
		// Field 95: reboot_seconds (int32)
		n := EncodeVarint(tmp, EncodeTag(95, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(v.RebootSeconds))
		buf = append(buf, tmp[:n]...)

	case *AdminMessage_ShutdownSeconds:
		// Field 96: shutdown_seconds (int32)
		n := EncodeVarint(tmp, EncodeTag(96, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(v.ShutdownSeconds))
		buf = append(buf, tmp[:n]...)

	case *AdminMessage_FactoryReset:
		// Field 94: factory_reset (int32)
		n := EncodeVarint(tmp, EncodeTag(94, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(v.FactoryReset))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalConfig encodes a Config message to protobuf wire format.
func MarshalConfig(c *Config) ([]byte, error) {
	if c == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	switch v := c.PayloadVariant.(type) {
	case *Config_Device:
		if v.Device != nil {
			data, err := MarshalDeviceConfig(v.Device)
			if err != nil {
				return nil, err
			}
			// Field 1: device
			n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Position:
		if v.Position != nil {
			data, err := MarshalPositionConfig(v.Position)
			if err != nil {
				return nil, err
			}
			// Field 2: position
			n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Power:
		if v.Power != nil {
			data, err := MarshalPowerConfig(v.Power)
			if err != nil {
				return nil, err
			}
			// Field 3: power
			n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Network:
		if v.Network != nil {
			data, err := MarshalNetworkConfig(v.Network)
			if err != nil {
				return nil, err
			}
			// Field 4: network
			n := EncodeVarint(tmp, EncodeTag(4, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Display:
		if v.Display != nil {
			data, err := MarshalDisplayConfig(v.Display)
			if err != nil {
				return nil, err
			}
			// Field 5: display
			n := EncodeVarint(tmp, EncodeTag(5, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Lora:
		if v.Lora != nil {
			data, err := MarshalLoRaConfig(v.Lora)
			if err != nil {
				return nil, err
			}
			// Field 6: lora
			n := EncodeVarint(tmp, EncodeTag(6, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Bluetooth:
		if v.Bluetooth != nil {
			data, err := MarshalBluetoothConfig(v.Bluetooth)
			if err != nil {
				return nil, err
			}
			// Field 7: bluetooth
			n := EncodeVarint(tmp, EncodeTag(7, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *Config_Security:
		if v.Security != nil {
			data, err := MarshalSecurityConfig(v.Security)
			if err != nil {
				return nil, err
			}
			// Field 8: security
			n := EncodeVarint(tmp, EncodeTag(8, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}
	}

	return buf, nil
}

// MarshalDeviceConfig encodes a DeviceConfig to protobuf wire format.
func MarshalDeviceConfig(dc *Config_DeviceConfig) ([]byte, error) {
	if dc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	// Field 1: role (enum)
	if dc.Role != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.Role))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: serial_enabled (bool)
	if dc.SerialEnabled {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 3: debug_log_enabled (bool)
	if dc.DebugLogEnabled {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 4: button_gpio (uint32)
	if dc.ButtonGpio != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.ButtonGpio))
		buf = append(buf, tmp[:n]...)
	}

	// Field 5: buzzer_gpio (uint32)
	if dc.BuzzerGpio != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.BuzzerGpio))
		buf = append(buf, tmp[:n]...)
	}

	// Field 6: rebroadcast_mode (uint32)
	if dc.RebroadcastMode != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.RebroadcastMode))
		buf = append(buf, tmp[:n]...)
	}

	// Field 7: node_info_broadcast_secs (uint32)
	if dc.NodeInfoBroadcastSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.NodeInfoBroadcastSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 8: double_tap_as_button_press (bool)
	if dc.DoubleTapAsButtonPress {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 9: is_managed (bool)
	if dc.IsManaged {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 10: disable_triple_click (bool)
	if dc.DisableTripleClick {
		n := EncodeVarint(tmp, EncodeTag(10, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 11: tzdef (string)
	if dc.Tzdef != "" {
		n := EncodeVarint(tmp, EncodeTag(11, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(dc.Tzdef)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(dc.Tzdef)...)
	}

	// Field 12: led_heartbeat_disabled (bool)
	if dc.LedHeartbeatDisabled {
		n := EncodeVarint(tmp, EncodeTag(12, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalPositionConfig encodes a PositionConfig to protobuf wire format.
func MarshalPositionConfig(pc *Config_PositionConfig) ([]byte, error) {
	if pc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	// Field 1: position_broadcast_secs
	if pc.PositionBroadcastSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.PositionBroadcastSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: position_broadcast_smart_enabled
	if pc.PositionBroadcastSmartEnabled {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 3: fixed_position
	if pc.FixedPosition {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 4: gps_enabled
	if pc.GpsEnabled {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 5: gps_update_interval
	if pc.GpsUpdateInterval != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.GpsUpdateInterval))
		buf = append(buf, tmp[:n]...)
	}

	// Field 6: gps_attempt_time
	if pc.GpsAttemptTime != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.GpsAttemptTime))
		buf = append(buf, tmp[:n]...)
	}

	// Field 7: position_flags
	if pc.PositionFlags != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.PositionFlags))
		buf = append(buf, tmp[:n]...)
	}

	// Field 12: gps_mode
	if pc.GpsMode != 0 {
		n := EncodeVarint(tmp, EncodeTag(12, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.GpsMode))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalPowerConfig encodes a PowerConfig to protobuf wire format.
func MarshalPowerConfig(pc *Config_PowerConfig) ([]byte, error) {
	if pc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	// Field 1: is_power_saving
	if pc.IsPowerSaving {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 2: on_battery_shutdown_after_secs
	if pc.OnBatteryShutdownAfterSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.OnBatteryShutdownAfterSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 3: adc_multiplier_override (float32)
	if pc.AdcMultiplierOverride != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, math.Float32bits(pc.AdcMultiplierOverride))
		buf = append(buf, b...)
	}

	// Field 4: wait_bluetooth_secs
	if pc.WaitBluetoothSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.WaitBluetoothSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 6: sds_secs
	if pc.SdsSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.SdsSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 7: ls_secs
	if pc.LsSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.LsSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 8: min_wake_secs
	if pc.MinWakeSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(pc.MinWakeSecs))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalNetworkConfig encodes a NetworkConfig to protobuf wire format.
func MarshalNetworkConfig(nc *Config_NetworkConfig) ([]byte, error) {
	if nc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: wifi_enabled
	if nc.WifiEnabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 3: wifi_ssid
	if nc.WifiSsid != "" {
		n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(nc.WifiSsid)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(nc.WifiSsid)...)
	}

	// Field 4: wifi_psk
	if nc.WifiPsk != "" {
		n := EncodeVarint(tmp, EncodeTag(4, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(nc.WifiPsk)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(nc.WifiPsk)...)
	}

	// Field 5: ntp_server
	if nc.NtpServer != "" {
		n := EncodeVarint(tmp, EncodeTag(5, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(nc.NtpServer)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(nc.NtpServer)...)
	}

	// Field 6: eth_enabled
	if nc.EthEnabled {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 7: address_mode
	if nc.AddressMode != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(nc.AddressMode))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalDisplayConfig encodes a DisplayConfig to protobuf wire format.
func MarshalDisplayConfig(dc *Config_DisplayConfig) ([]byte, error) {
	if dc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	// Field 1: screen_on_secs
	if dc.ScreenOnSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.ScreenOnSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: gps_format
	if dc.GpsFormat != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.GpsFormat))
		buf = append(buf, tmp[:n]...)
	}

	// Field 3: auto_screen_carousel_secs
	if dc.AutoScreenCarouselSecs != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.AutoScreenCarouselSecs))
		buf = append(buf, tmp[:n]...)
	}

	// Field 4: compass_north_top
	if dc.CompassNorthTop {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 5: flip_screen
	if dc.FlipScreen {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 6: units
	if dc.Units != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.Units))
		buf = append(buf, tmp[:n]...)
	}

	// Field 7: oled
	if dc.Oled != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.Oled))
		buf = append(buf, tmp[:n]...)
	}

	// Field 8: display_mode
	if dc.DisplayMode != 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(dc.DisplayMode))
		buf = append(buf, tmp[:n]...)
	}

	// Field 9: heading_bold
	if dc.HeadingBold {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 10: wake_on_tap_or_motion
	if dc.WakeOnTapOrMotion {
		n := EncodeVarint(tmp, EncodeTag(10, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalBluetoothConfig encodes a BluetoothConfig to protobuf wire format.
func MarshalBluetoothConfig(bc *Config_BluetoothConfig) ([]byte, error) {
	if bc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 32)
	tmp := make([]byte, 10)

	// Field 1: enabled
	if bc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 2: mode (enum)
	if bc.Mode != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(bc.Mode))
		buf = append(buf, tmp[:n]...)
	}

	// Field 3: fixed_pin
	if bc.FixedPin != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(bc.FixedPin))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalSecurityConfig encodes a SecurityConfig to protobuf wire format.
func MarshalSecurityConfig(sc *Config_SecurityConfig) ([]byte, error) {
	if sc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: public_key
	if len(sc.PublicKey) > 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(sc.PublicKey)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, sc.PublicKey...)
	}

	// Field 2: private_key
	if len(sc.PrivateKey) > 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(sc.PrivateKey)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, sc.PrivateKey...)
	}

	// Field 3: admin_key
	if len(sc.AdminKey) > 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(sc.AdminKey)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, sc.AdminKey...)
	}

	// Field 4: is_managed
	if sc.IsManaged {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 5: serial_enabled
	if sc.SerialEnabled {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 6: debug_log_api_enabled
	if sc.DebugLogApiEnabled {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 8: admin_channel_enabled
	if sc.AdminChannelEnabled {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalModuleConfig encodes a ModuleConfig message to protobuf wire format.
func MarshalModuleConfig(mc *ModuleConfig) ([]byte, error) {
	if mc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	switch v := mc.PayloadVariant.(type) {
	case *ModuleConfig_Mqtt:
		if v.Mqtt != nil {
			data, err := MarshalMQTTConfig(v.Mqtt)
			if err != nil {
				return nil, err
			}
			// Field 1: mqtt
			n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_Serial:
		if v.Serial != nil {
			data, err := MarshalSerialConfig(v.Serial)
			if err != nil {
				return nil, err
			}
			// Field 2: serial
			n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_ExternalNotification:
		if v.ExternalNotification != nil {
			data, err := MarshalExternalNotificationConfig(v.ExternalNotification)
			if err != nil {
				return nil, err
			}
			// Field 3: external_notification
			n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_StoreForward:
		if v.StoreForward != nil {
			data, err := MarshalStoreForwardConfig(v.StoreForward)
			if err != nil {
				return nil, err
			}
			// Field 4: store_forward
			n := EncodeVarint(tmp, EncodeTag(4, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_RangeTest:
		if v.RangeTest != nil {
			data, err := MarshalRangeTestConfig(v.RangeTest)
			if err != nil {
				return nil, err
			}
			// Field 5: range_test
			n := EncodeVarint(tmp, EncodeTag(5, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_Telemetry:
		if v.Telemetry != nil {
			data, err := MarshalTelemetryConfig(v.Telemetry)
			if err != nil {
				return nil, err
			}
			// Field 6: telemetry
			n := EncodeVarint(tmp, EncodeTag(6, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_CannedMessage:
		if v.CannedMessage != nil {
			data, err := MarshalCannedMessageConfig(v.CannedMessage)
			if err != nil {
				return nil, err
			}
			// Field 7: canned_message
			n := EncodeVarint(tmp, EncodeTag(7, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}

	case *ModuleConfig_NeighborInfo:
		if v.NeighborInfo != nil {
			data, err := MarshalNeighborInfoConfig(v.NeighborInfo)
			if err != nil {
				return nil, err
			}
			// Field 10: neighbor_info
			n := EncodeVarint(tmp, EncodeTag(10, WireBytes))
			buf = append(buf, tmp[:n]...)
			n = EncodeVarint(tmp, uint64(len(data)))
			buf = append(buf, tmp[:n]...)
			buf = append(buf, data...)
		}
	}

	return buf, nil
}

// MarshalMQTTConfig encodes an MQTTConfig to protobuf wire format.
func MarshalMQTTConfig(mc *ModuleConfig_MQTTConfig) ([]byte, error) {
	if mc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	if mc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if mc.Address != "" {
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(mc.Address)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(mc.Address)...)
	}

	if mc.Username != "" {
		n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(mc.Username)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(mc.Username)...)
	}

	if mc.Password != "" {
		n := EncodeVarint(tmp, EncodeTag(4, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(mc.Password)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(mc.Password)...)
	}

	if mc.EncryptionEnabled {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if mc.JsonEnabled {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if mc.TlsEnabled {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if mc.Root != "" {
		n := EncodeVarint(tmp, EncodeTag(8, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(mc.Root)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(mc.Root)...)
	}

	if mc.ProxyToClientEnabled {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if mc.MapReportingEnabled {
		n := EncodeVarint(tmp, EncodeTag(10, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalSerialConfig encodes a SerialConfig to protobuf wire format.
func MarshalSerialConfig(sc *ModuleConfig_SerialConfig) ([]byte, error) {
	if sc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	if sc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if sc.Echo {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if sc.RxD != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sc.RxD))
		buf = append(buf, tmp[:n]...)
	}

	if sc.TxD != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sc.TxD))
		buf = append(buf, tmp[:n]...)
	}

	if sc.Baud != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sc.Baud))
		buf = append(buf, tmp[:n]...)
	}

	if sc.Timeout != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sc.Timeout))
		buf = append(buf, tmp[:n]...)
	}

	if sc.Mode != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sc.Mode))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalExternalNotificationConfig encodes an ExternalNotificationConfig to protobuf wire format.
func MarshalExternalNotificationConfig(enc *ModuleConfig_ExternalNotificationConfig) ([]byte, error) {
	if enc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	if enc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if enc.OutputMs != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(enc.OutputMs))
		buf = append(buf, tmp[:n]...)
	}

	if enc.Output != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(enc.Output))
		buf = append(buf, tmp[:n]...)
	}

	if enc.Active {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if enc.AlertMessage {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if enc.AlertBell {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if enc.UsePwm {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalStoreForwardConfig encodes a StoreForwardConfig to protobuf wire format.
func MarshalStoreForwardConfig(sfc *ModuleConfig_StoreForwardConfig) ([]byte, error) {
	if sfc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 32)
	tmp := make([]byte, 10)

	if sfc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if sfc.Heartbeat {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if sfc.Records != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sfc.Records))
		buf = append(buf, tmp[:n]...)
	}

	if sfc.HistoryReturnMax != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sfc.HistoryReturnMax))
		buf = append(buf, tmp[:n]...)
	}

	if sfc.HistoryReturnWindow != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(sfc.HistoryReturnWindow))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalRangeTestConfig encodes a RangeTestConfig to protobuf wire format.
func MarshalRangeTestConfig(rtc *ModuleConfig_RangeTestConfig) ([]byte, error) {
	if rtc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 16)
	tmp := make([]byte, 10)

	if rtc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if rtc.Sender != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(rtc.Sender))
		buf = append(buf, tmp[:n]...)
	}

	if rtc.Save {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalTelemetryConfig encodes a TelemetryConfig to protobuf wire format.
func MarshalTelemetryConfig(tc *ModuleConfig_TelemetryConfig) ([]byte, error) {
	if tc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	if tc.DeviceUpdateInterval != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(tc.DeviceUpdateInterval))
		buf = append(buf, tmp[:n]...)
	}

	if tc.EnvironmentUpdateInterval != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(tc.EnvironmentUpdateInterval))
		buf = append(buf, tmp[:n]...)
	}

	if tc.EnvironmentMeasurementEnabled {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if tc.EnvironmentScreenEnabled {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if tc.EnvironmentDisplayFahrenheit {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if tc.AirQualityEnabled {
		n := EncodeVarint(tmp, EncodeTag(6, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if tc.AirQualityInterval != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(tc.AirQualityInterval))
		buf = append(buf, tmp[:n]...)
	}

	if tc.PowerMeasurementEnabled {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if tc.PowerUpdateInterval != 0 {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(tc.PowerUpdateInterval))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalCannedMessageConfig encodes a CannedMessageConfig to protobuf wire format.
func MarshalCannedMessageConfig(cmc *ModuleConfig_CannedMessageConfig) ([]byte, error) {
	if cmc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	if cmc.RotaryEnabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if cmc.InputbrokerPinA != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(cmc.InputbrokerPinA))
		buf = append(buf, tmp[:n]...)
	}

	if cmc.InputbrokerPinB != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(cmc.InputbrokerPinB))
		buf = append(buf, tmp[:n]...)
	}

	if cmc.InputbrokerPinPress != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(cmc.InputbrokerPinPress))
		buf = append(buf, tmp[:n]...)
	}

	if cmc.UpsideDown {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if cmc.Enabled {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if cmc.AllowInputSource != "" {
		n := EncodeVarint(tmp, EncodeTag(10, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(cmc.AllowInputSource)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(cmc.AllowInputSource)...)
	}

	if cmc.SendBell {
		n := EncodeVarint(tmp, EncodeTag(11, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	return buf, nil
}

// MarshalNeighborInfoConfig encodes a NeighborInfoConfig to protobuf wire format.
func MarshalNeighborInfoConfig(nic *ModuleConfig_NeighborInfoConfig) ([]byte, error) {
	if nic == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 16)
	tmp := make([]byte, 10)

	if nic.Enabled {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	if nic.UpdateInterval != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(nic.UpdateInterval))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// UnmarshalRouteDiscovery decodes a RouteDiscovery message from protobuf wire format.
func UnmarshalRouteDiscovery(buf []byte) (*RouteDiscovery, error) {
	rd := &RouteDiscovery{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // route (repeated fixed32, packed)
			if wireType == WireBytes {
				// Packed repeated field
				length, ln := DecodeVarint(buf[offset:])
				if ln == 0 {
					break
				}
				offset += ln
				end := offset + int(length)
				if end > len(buf) {
					break
				}
				for offset+4 <= end {
					rd.Route = append(rd.Route, binary.LittleEndian.Uint32(buf[offset:]))
					offset += 4
				}
			} else if wireType == WireFixed32 {
				// Non-packed single value
				if offset+4 > len(buf) {
					break
				}
				rd.Route = append(rd.Route, binary.LittleEndian.Uint32(buf[offset:]))
				offset += 4
			}

		case 2: // snr_towards (repeated sint32, packed zigzag)
			if wireType == WireBytes {
				length, ln := DecodeVarint(buf[offset:])
				if ln == 0 {
					break
				}
				offset += ln
				end := offset + int(length)
				if end > len(buf) {
					break
				}
				for offset < end {
					v, vn := DecodeVarint(buf[offset:])
					if vn == 0 {
						break
					}
					rd.SnrTowards = append(rd.SnrTowards, int32(DecodeZigZag(v)))
					offset += vn
				}
			} else if wireType == WireVarint {
				v, vn := DecodeVarint(buf[offset:])
				if vn == 0 {
					break
				}
				rd.SnrTowards = append(rd.SnrTowards, int32(DecodeZigZag(v)))
				offset += vn
			}

		case 3: // route_back (repeated fixed32, packed)
			if wireType == WireBytes {
				length, ln := DecodeVarint(buf[offset:])
				if ln == 0 {
					break
				}
				offset += ln
				end := offset + int(length)
				if end > len(buf) {
					break
				}
				for offset+4 <= end {
					rd.RouteBack = append(rd.RouteBack, binary.LittleEndian.Uint32(buf[offset:]))
					offset += 4
				}
			} else if wireType == WireFixed32 {
				if offset+4 > len(buf) {
					break
				}
				rd.RouteBack = append(rd.RouteBack, binary.LittleEndian.Uint32(buf[offset:]))
				offset += 4
			}

		case 4: // snr_back (repeated sint32, packed zigzag)
			if wireType == WireBytes {
				length, ln := DecodeVarint(buf[offset:])
				if ln == 0 {
					break
				}
				offset += ln
				end := offset + int(length)
				if end > len(buf) {
					break
				}
				for offset < end {
					v, vn := DecodeVarint(buf[offset:])
					if vn == 0 {
						break
					}
					rd.SnrBack = append(rd.SnrBack, int32(DecodeZigZag(v)))
					offset += vn
				}
			} else if wireType == WireVarint {
				v, vn := DecodeVarint(buf[offset:])
				if vn == 0 {
					break
				}
				rd.SnrBack = append(rd.SnrBack, int32(DecodeZigZag(v)))
				offset += vn
			}

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return rd, nil
}

// UnmarshalNeighborInfo decodes a NeighborInfo message from protobuf wire format.
func UnmarshalNeighborInfo(buf []byte) (*NeighborInfo, error) {
	if len(buf) == 0 {
		return nil, nil
	}

	ni := &NeighborInfo{
		Neighbors: make([]*Neighbor, 0),
	}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // node_id (uint32)
			if wireType != WireVarint {
				offset = skipField(buf, offset, wireType)
				continue
			}
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			ni.NodeId = uint32(v)
			offset += vn

		case 2: // last_sent_by_id (uint32)
			if wireType != WireVarint {
				offset = skipField(buf, offset, wireType)
				continue
			}
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			ni.LastSentById = uint32(v)
			offset += vn

		case 3: // node_broadcast_interval_secs (uint32)
			if wireType != WireVarint {
				offset = skipField(buf, offset, wireType)
				continue
			}
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			ni.NodeBroadcastIntervalSecs = uint32(v)
			offset += vn

		case 4: // neighbors (repeated Neighbor)
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				break
			}
			offset += ln
			end := offset + int(length)
			if end > len(buf) {
				break
			}
			neighbor, err := unmarshalNeighbor(buf[offset:end])
			if err == nil && neighbor != nil {
				ni.Neighbors = append(ni.Neighbors, neighbor)
			}
			offset = end

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return ni, nil
}

// unmarshalNeighbor decodes a single Neighbor message.
func unmarshalNeighbor(buf []byte) (*Neighbor, error) {
	if len(buf) == 0 {
		return nil, nil
	}

	n := &Neighbor{}
	offset := 0

	for offset < len(buf) {
		tag, tn := DecodeVarint(buf[offset:])
		if tn == 0 {
			break
		}
		offset += tn

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // node_id (uint32)
			if wireType != WireVarint {
				offset = skipField(buf, offset, wireType)
				continue
			}
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			n.NodeId = uint32(v)
			offset += vn

		case 2: // snr (float32, fixed32)
			if wireType != WireFixed32 {
				offset = skipField(buf, offset, wireType)
				continue
			}
			if offset+4 > len(buf) {
				break
			}
			bits := binary.LittleEndian.Uint32(buf[offset:])
			n.Snr = math.Float32frombits(bits)
			offset += 4

		case 3: // last_rx_time (fixed32)
			if wireType != WireFixed32 {
				offset = skipField(buf, offset, wireType)
				continue
			}
			if offset+4 > len(buf) {
				break
			}
			n.LastRxTime = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		case 4: // node_broadcast_interval_secs (uint32)
			if wireType != WireVarint {
				offset = skipField(buf, offset, wireType)
				continue
			}
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				break
			}
			n.NodeBroadcastIntervalSecs = uint32(v)
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return n, nil
}

// MarshalChannelSet encodes a ChannelSet to protobuf wire format.
// Used for generating channel share URLs.
func MarshalChannelSet(cs *ChannelSet) ([]byte, error) {
	if cs == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 256)
	tmp := make([]byte, 10)

	// Field 1: settings (repeated ChannelSettings)
	for _, s := range cs.Settings {
		settingsData, err := MarshalChannelSettings(s)
		if err != nil {
			return nil, err
		}
		n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(settingsData)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, settingsData...)
	}

	// Field 2: lora_config (LoRaConfig)
	if cs.LoraConfig != nil {
		loraData, err := MarshalLoRaConfig(cs.LoraConfig)
		if err != nil {
			return nil, err
		}
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(loraData)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, loraData...)
	}

	return buf, nil
}

// UnmarshalChannelSet decodes a ChannelSet from protobuf wire format.
// Used for parsing channel share URLs.
func UnmarshalChannelSet(buf []byte) (*ChannelSet, error) {
	if len(buf) == 0 {
		return nil, nil
	}

	cs := &ChannelSet{
		Settings: make([]*ChannelSettings, 0),
	}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			break
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // settings (repeated ChannelSettings)
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				break
			}
			offset += ln
			end := offset + int(length)
			if end > len(buf) {
				break
			}
			settings, err := UnmarshalChannelSettings(buf[offset:end])
			if err != nil {
				return nil, err
			}
			cs.Settings = append(cs.Settings, settings)
			offset = end

		case 2: // lora_config (LoRaConfig)
			if wireType != WireBytes {
				offset = skipField(buf, offset, wireType)
				continue
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				break
			}
			offset += ln
			end := offset + int(length)
			if end > len(buf) {
				break
			}
			loraConfig, err := UnmarshalLoRaConfig(buf[offset:end])
			if err != nil {
				return nil, err
			}
			cs.LoraConfig = loraConfig
			offset = end

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				break
			}
		}
	}

	return cs, nil
}

// MarshalLoRaConfig encodes a LoRaConfig to protobuf wire format.
func MarshalLoRaConfig(lc *Config_LoRaConfig) ([]byte, error) {
	if lc == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 64)
	tmp := make([]byte, 10)

	// Field 1: use_preset (bool)
	if lc.UsePreset {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 2: modem_preset (enum)
	if lc.ModemPreset != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.ModemPreset))
		buf = append(buf, tmp[:n]...)
	}

	// Field 3: bandwidth (uint32)
	if lc.Bandwidth != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.Bandwidth))
		buf = append(buf, tmp[:n]...)
	}

	// Field 4: spread_factor (uint32)
	if lc.SpreadFactor != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.SpreadFactor))
		buf = append(buf, tmp[:n]...)
	}

	// Field 5: coding_rate (uint32)
	if lc.CodingRate != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.CodingRate))
		buf = append(buf, tmp[:n]...)
	}

	// Field 6: frequency_offset (float32)
	if lc.FrequencyOffset != 0 {
		n := EncodeVarint(tmp, EncodeTag(6, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, math.Float32bits(lc.FrequencyOffset))
		buf = append(buf, b...)
	}

	// Field 7: region (enum)
	if lc.Region != 0 {
		n := EncodeVarint(tmp, EncodeTag(7, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.Region))
		buf = append(buf, tmp[:n]...)
	}

	// Field 8: hop_limit (uint32)
	if lc.HopLimit != 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.HopLimit))
		buf = append(buf, tmp[:n]...)
	}

	// Field 9: tx_enabled (bool)
	if lc.TxEnabled {
		n := EncodeVarint(tmp, EncodeTag(9, WireVarint))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, 1)
	}

	// Field 10: tx_power (int32)
	if lc.TxPower != 0 {
		n := EncodeVarint(tmp, EncodeTag(10, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.TxPower))
		buf = append(buf, tmp[:n]...)
	}

	// Field 11: channel_num (uint32)
	if lc.ChannelNum != 0 {
		n := EncodeVarint(tmp, EncodeTag(11, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(lc.ChannelNum))
		buf = append(buf, tmp[:n]...)
	}

	return buf, nil
}

// MarshalServiceEnvelope encodes a ServiceEnvelope to protobuf wire format.
func MarshalServiceEnvelope(s *ServiceEnvelope) ([]byte, error) {
	if s == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 256)
	tmp := make([]byte, 10)

	// Field 1: packet (MeshPacket)
	if s.Packet != nil {
		packetData, err := MarshalMeshPacket(s.Packet)
		if err != nil {
			return nil, err
		}
		n := EncodeVarint(tmp, EncodeTag(1, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(packetData)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, packetData...)
	}

	// Field 2: channel_id (string)
	if s.ChannelId != "" {
		n := EncodeVarint(tmp, EncodeTag(2, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(s.ChannelId)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(s.ChannelId)...)
	}

	// Field 3: gateway_id (string)
	if s.GatewayId != "" {
		n := EncodeVarint(tmp, EncodeTag(3, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(s.GatewayId)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(s.GatewayId)...)
	}

	return buf, nil
}

// UnmarshalServiceEnvelope decodes a ServiceEnvelope from protobuf wire format.
func UnmarshalServiceEnvelope(buf []byte) (*ServiceEnvelope, error) {
	s := &ServiceEnvelope{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // packet
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			packet, err := UnmarshalMeshPacket(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			s.Packet = packet
			offset += int(length)

		case 2: // channel_id
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			s.ChannelId = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 3: // gateway_id
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			s.GatewayId = string(buf[offset : offset+int(length)])
			offset += int(length)

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return s, nil
}

// MarshalWaypoint encodes a Waypoint to protobuf wire format.
func MarshalWaypoint(w *Waypoint) ([]byte, error) {
	if w == nil {
		return nil, nil
	}

	buf := make([]byte, 0, 128)
	tmp := make([]byte, 10)

	// Field 1: id (uint32 varint)
	if w.Id != 0 {
		n := EncodeVarint(tmp, EncodeTag(1, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(w.Id))
		buf = append(buf, tmp[:n]...)
	}

	// Field 2: latitude_i (sfixed32)
	if w.LatitudeI != 0 {
		n := EncodeVarint(tmp, EncodeTag(2, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, uint32(w.LatitudeI))
		buf = append(buf, b...)
	}

	// Field 3: longitude_i (sfixed32)
	if w.LongitudeI != 0 {
		n := EncodeVarint(tmp, EncodeTag(3, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, uint32(w.LongitudeI))
		buf = append(buf, b...)
	}

	// Field 4: expire (uint32 varint)
	if w.Expire != 0 {
		n := EncodeVarint(tmp, EncodeTag(4, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(w.Expire))
		buf = append(buf, tmp[:n]...)
	}

	// Field 5: locked_to (uint32 varint)
	if w.LockedTo != 0 {
		n := EncodeVarint(tmp, EncodeTag(5, WireVarint))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(w.LockedTo))
		buf = append(buf, tmp[:n]...)
	}

	// Field 6: name (string)
	if w.Name != "" {
		n := EncodeVarint(tmp, EncodeTag(6, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(w.Name)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(w.Name)...)
	}

	// Field 7: description (string)
	if w.Description != "" {
		n := EncodeVarint(tmp, EncodeTag(7, WireBytes))
		buf = append(buf, tmp[:n]...)
		n = EncodeVarint(tmp, uint64(len(w.Description)))
		buf = append(buf, tmp[:n]...)
		buf = append(buf, []byte(w.Description)...)
	}

	// Field 8: icon (fixed32)
	if w.Icon != 0 {
		n := EncodeVarint(tmp, EncodeTag(8, WireFixed32))
		buf = append(buf, tmp[:n]...)
		b := make([]byte, 4)
		binary.LittleEndian.PutUint32(b, w.Icon)
		buf = append(buf, b...)
	}

	return buf, nil
}

// UnmarshalWaypoint decodes a Waypoint from protobuf wire format.
func UnmarshalWaypoint(buf []byte) (*Waypoint, error) {
	w := &Waypoint{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // id
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			w.Id = uint32(v)
			offset += n

		case 2: // latitude_i
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			w.LatitudeI = int32(binary.LittleEndian.Uint32(buf[offset:]))
			offset += 4

		case 3: // longitude_i
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			w.LongitudeI = int32(binary.LittleEndian.Uint32(buf[offset:]))
			offset += 4

		case 4: // expire
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			w.Expire = uint32(v)
			offset += n

		case 5: // locked_to
			v, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			w.LockedTo = uint32(v)
			offset += n

		case 6: // name
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			w.Name = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 7: // description
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, n := DecodeVarint(buf[offset:])
			if n == 0 {
				return nil, ErrInvalidData
			}
			offset += n
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			w.Description = string(buf[offset : offset+int(length)])
			offset += int(length)

		case 8: // icon
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			w.Icon = binary.LittleEndian.Uint32(buf[offset:])
			offset += 4

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return w, nil
}
