// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Source: meshtastic/config.proto

package pb

// Config_DeviceConfig_Role defines the node role in the mesh.
type Config_DeviceConfig_Role int32

const (
	Config_DeviceConfig_CLIENT          Config_DeviceConfig_Role = 0
	Config_DeviceConfig_CLIENT_MUTE     Config_DeviceConfig_Role = 1
	Config_DeviceConfig_ROUTER          Config_DeviceConfig_Role = 2
	Config_DeviceConfig_ROUTER_CLIENT   Config_DeviceConfig_Role = 3
	Config_DeviceConfig_REPEATER        Config_DeviceConfig_Role = 4
	Config_DeviceConfig_TRACKER         Config_DeviceConfig_Role = 5
	Config_DeviceConfig_SENSOR          Config_DeviceConfig_Role = 6
	Config_DeviceConfig_TAK             Config_DeviceConfig_Role = 7
	Config_DeviceConfig_CLIENT_HIDDEN   Config_DeviceConfig_Role = 8
	Config_DeviceConfig_LOST_AND_FOUND  Config_DeviceConfig_Role = 9
	Config_DeviceConfig_TAK_TRACKER     Config_DeviceConfig_Role = 10
)

var Config_DeviceConfig_Role_name = map[int32]string{
	0:  "CLIENT",
	1:  "CLIENT_MUTE",
	2:  "ROUTER",
	3:  "ROUTER_CLIENT",
	4:  "REPEATER",
	5:  "TRACKER",
	6:  "SENSOR",
	7:  "TAK",
	8:  "CLIENT_HIDDEN",
	9:  "LOST_AND_FOUND",
	10: "TAK_TRACKER",
}

func (x Config_DeviceConfig_Role) String() string {
	if s, ok := Config_DeviceConfig_Role_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// Config_LoRaConfig_RegionCode defines the LoRa region.
type Config_LoRaConfig_RegionCode int32

const (
	Config_LoRaConfig_UNSET     Config_LoRaConfig_RegionCode = 0
	Config_LoRaConfig_US        Config_LoRaConfig_RegionCode = 1
	Config_LoRaConfig_EU_433    Config_LoRaConfig_RegionCode = 2
	Config_LoRaConfig_EU_868    Config_LoRaConfig_RegionCode = 3
	Config_LoRaConfig_CN        Config_LoRaConfig_RegionCode = 4
	Config_LoRaConfig_JP        Config_LoRaConfig_RegionCode = 5
	Config_LoRaConfig_ANZ       Config_LoRaConfig_RegionCode = 6
	Config_LoRaConfig_KR        Config_LoRaConfig_RegionCode = 7
	Config_LoRaConfig_TW        Config_LoRaConfig_RegionCode = 8
	Config_LoRaConfig_RU        Config_LoRaConfig_RegionCode = 9
	Config_LoRaConfig_IN        Config_LoRaConfig_RegionCode = 10
	Config_LoRaConfig_NZ_865    Config_LoRaConfig_RegionCode = 11
	Config_LoRaConfig_TH        Config_LoRaConfig_RegionCode = 12
	Config_LoRaConfig_LORA_24   Config_LoRaConfig_RegionCode = 13
	Config_LoRaConfig_UA_433    Config_LoRaConfig_RegionCode = 14
	Config_LoRaConfig_UA_868    Config_LoRaConfig_RegionCode = 15
	Config_LoRaConfig_MY_433    Config_LoRaConfig_RegionCode = 16
	Config_LoRaConfig_MY_919    Config_LoRaConfig_RegionCode = 17
	Config_LoRaConfig_SG_923    Config_LoRaConfig_RegionCode = 18
	Config_LoRaConfig_PH_433    Config_LoRaConfig_RegionCode = 19
	Config_LoRaConfig_PH_868    Config_LoRaConfig_RegionCode = 20
	Config_LoRaConfig_PH_915    Config_LoRaConfig_RegionCode = 21
	Config_LoRaConfig_UNSET_2   Config_LoRaConfig_RegionCode = 22
	Config_LoRaConfig_UNSET_3   Config_LoRaConfig_RegionCode = 23
	Config_LoRaConfig_UNSET_4   Config_LoRaConfig_RegionCode = 24
	Config_LoRaConfig_UNSET_5   Config_LoRaConfig_RegionCode = 25
)

var Config_LoRaConfig_RegionCode_name = map[int32]string{
	0:  "UNSET",
	1:  "US",
	2:  "EU_433",
	3:  "EU_868",
	4:  "CN",
	5:  "JP",
	6:  "ANZ",
	7:  "KR",
	8:  "TW",
	9:  "RU",
	10: "IN",
	11: "NZ_865",
	12: "TH",
	13: "LORA_24",
	14: "UA_433",
	15: "UA_868",
	16: "MY_433",
	17: "MY_919",
	18: "SG_923",
	19: "PH_433",
	20: "PH_868",
	21: "PH_915",
}

func (x Config_LoRaConfig_RegionCode) String() string {
	if s, ok := Config_LoRaConfig_RegionCode_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// Config_LoRaConfig_ModemPreset defines modem presets.
type Config_LoRaConfig_ModemPreset int32

const (
	Config_LoRaConfig_LONG_FAST    Config_LoRaConfig_ModemPreset = 0
	Config_LoRaConfig_LONG_SLOW    Config_LoRaConfig_ModemPreset = 1
	Config_LoRaConfig_VERY_LONG_SLOW Config_LoRaConfig_ModemPreset = 2
	Config_LoRaConfig_MEDIUM_SLOW  Config_LoRaConfig_ModemPreset = 3
	Config_LoRaConfig_MEDIUM_FAST  Config_LoRaConfig_ModemPreset = 4
	Config_LoRaConfig_SHORT_SLOW   Config_LoRaConfig_ModemPreset = 5
	Config_LoRaConfig_SHORT_FAST   Config_LoRaConfig_ModemPreset = 6
	Config_LoRaConfig_LONG_MODERATE Config_LoRaConfig_ModemPreset = 7
	Config_LoRaConfig_SHORT_TURBO  Config_LoRaConfig_ModemPreset = 8
)

var Config_LoRaConfig_ModemPreset_name = map[int32]string{
	0: "LONG_FAST",
	1: "LONG_SLOW",
	2: "VERY_LONG_SLOW",
	3: "MEDIUM_SLOW",
	4: "MEDIUM_FAST",
	5: "SHORT_SLOW",
	6: "SHORT_FAST",
	7: "LONG_MODERATE",
	8: "SHORT_TURBO",
}

func (x Config_LoRaConfig_ModemPreset) String() string {
	if s, ok := Config_LoRaConfig_ModemPreset_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// Config_BluetoothConfig_PairingMode defines Bluetooth pairing modes.
type Config_BluetoothConfig_PairingMode int32

const (
	Config_BluetoothConfig_RANDOM_PIN Config_BluetoothConfig_PairingMode = 0
	Config_BluetoothConfig_FIXED_PIN  Config_BluetoothConfig_PairingMode = 1
	Config_BluetoothConfig_NO_PIN     Config_BluetoothConfig_PairingMode = 2
)

// DeviceConfig contains device-specific settings.
type Config_DeviceConfig struct {
	Role                      uint32 `protobuf:"varint,1,opt,name=role,proto3,enum=meshtastic.Config_DeviceConfig_Role" json:"role,omitempty"`
	SerialEnabled             bool   `protobuf:"varint,2,opt,name=serial_enabled,json=serialEnabled,proto3" json:"serialEnabled,omitempty"`
	DebugLogEnabled           bool   `protobuf:"varint,3,opt,name=debug_log_enabled,json=debugLogEnabled,proto3" json:"debugLogEnabled,omitempty"`
	ButtonGpio                uint32 `protobuf:"varint,4,opt,name=button_gpio,json=buttonGpio,proto3" json:"buttonGpio,omitempty"`
	BuzzerGpio                uint32 `protobuf:"varint,5,opt,name=buzzer_gpio,json=buzzerGpio,proto3" json:"buzzerGpio,omitempty"`
	RebroadcastMode           uint32 `protobuf:"varint,6,opt,name=rebroadcast_mode,json=rebroadcastMode,proto3" json:"rebroadcastMode,omitempty"`
	NodeInfoBroadcastSecs     uint32 `protobuf:"varint,7,opt,name=node_info_broadcast_secs,json=nodeInfoBroadcastSecs,proto3" json:"nodeInfoBroadcastSecs,omitempty"`
	DoubleTapAsButtonPress    bool   `protobuf:"varint,8,opt,name=double_tap_as_button_press,json=doubleTapAsButtonPress,proto3" json:"doubleTapAsButtonPress,omitempty"`
	IsManaged                 bool   `protobuf:"varint,9,opt,name=is_managed,json=isManaged,proto3" json:"isManaged,omitempty"`
	DisableTripleClick        bool   `protobuf:"varint,10,opt,name=disable_triple_click,json=disableTripleClick,proto3" json:"disableTripleClick,omitempty"`
	Tzdef                     string `protobuf:"bytes,11,opt,name=tzdef,proto3" json:"tzdef,omitempty"`
	LedHeartbeatDisabled      bool   `protobuf:"varint,12,opt,name=led_heartbeat_disabled,json=ledHeartbeatDisabled,proto3" json:"ledHeartbeatDisabled,omitempty"`
}

func (c *Config_DeviceConfig) Reset() { *c = Config_DeviceConfig{} }
func (c *Config_DeviceConfig) ProtoMessage() {}

// PositionConfig contains GPS and position settings.
type Config_PositionConfig struct {
	PositionBroadcastSecs     uint32 `protobuf:"varint,1,opt,name=position_broadcast_secs,json=positionBroadcastSecs,proto3" json:"positionBroadcastSecs,omitempty"`
	PositionBroadcastSmartEnabled bool `protobuf:"varint,2,opt,name=position_broadcast_smart_enabled,json=positionBroadcastSmartEnabled,proto3" json:"positionBroadcastSmartEnabled,omitempty"`
	FixedPosition             bool   `protobuf:"varint,3,opt,name=fixed_position,json=fixedPosition,proto3" json:"fixedPosition,omitempty"`
	GpsEnabled                bool   `protobuf:"varint,4,opt,name=gps_enabled,json=gpsEnabled,proto3" json:"gpsEnabled,omitempty"`
	GpsUpdateInterval         uint32 `protobuf:"varint,5,opt,name=gps_update_interval,json=gpsUpdateInterval,proto3" json:"gpsUpdateInterval,omitempty"`
	GpsAttemptTime            uint32 `protobuf:"varint,6,opt,name=gps_attempt_time,json=gpsAttemptTime,proto3" json:"gpsAttemptTime,omitempty"`
	PositionFlags             uint32 `protobuf:"varint,7,opt,name=position_flags,json=positionFlags,proto3" json:"positionFlags,omitempty"`
	RxGpio                    uint32 `protobuf:"varint,8,opt,name=rx_gpio,json=rxGpio,proto3" json:"rxGpio,omitempty"`
	TxGpio                    uint32 `protobuf:"varint,9,opt,name=tx_gpio,json=txGpio,proto3" json:"txGpio,omitempty"`
	BroadcastSmartMinimumDistance uint32 `protobuf:"varint,10,opt,name=broadcast_smart_minimum_distance,json=broadcastSmartMinimumDistance,proto3" json:"broadcastSmartMinimumDistance,omitempty"`
	BroadcastSmartMinimumIntervalSecs uint32 `protobuf:"varint,11,opt,name=broadcast_smart_minimum_interval_secs,json=broadcastSmartMinimumIntervalSecs,proto3" json:"broadcastSmartMinimumIntervalSecs,omitempty"`
	GpsMode                   uint32 `protobuf:"varint,12,opt,name=gps_mode,json=gpsMode,proto3" json:"gpsMode,omitempty"`
}

func (c *Config_PositionConfig) Reset() { *c = Config_PositionConfig{} }
func (c *Config_PositionConfig) ProtoMessage() {}

// PowerConfig contains power management settings.
type Config_PowerConfig struct {
	IsPowerSaving            bool   `protobuf:"varint,1,opt,name=is_power_saving,json=isPowerSaving,proto3" json:"isPowerSaving,omitempty"`
	OnBatteryShutdownAfterSecs uint32 `protobuf:"varint,2,opt,name=on_battery_shutdown_after_secs,json=onBatteryShutdownAfterSecs,proto3" json:"onBatteryShutdownAfterSecs,omitempty"`
	AdcMultiplierOverride    float32 `protobuf:"fixed32,3,opt,name=adc_multiplier_override,json=adcMultiplierOverride,proto3" json:"adcMultiplierOverride,omitempty"`
	WaitBluetoothSecs        uint32 `protobuf:"varint,4,opt,name=wait_bluetooth_secs,json=waitBluetoothSecs,proto3" json:"waitBluetoothSecs,omitempty"`
	SdsSecs                  uint32 `protobuf:"varint,6,opt,name=sds_secs,json=sdsSecs,proto3" json:"sdsSecs,omitempty"`
	LsSecs                   uint32 `protobuf:"varint,7,opt,name=ls_secs,json=lsSecs,proto3" json:"lsSecs,omitempty"`
	MinWakeSecs              uint32 `protobuf:"varint,8,opt,name=min_wake_secs,json=minWakeSecs,proto3" json:"minWakeSecs,omitempty"`
	DeviceBatteryInaAddress  uint32 `protobuf:"varint,9,opt,name=device_battery_ina_address,json=deviceBatteryInaAddress,proto3" json:"deviceBatteryInaAddress,omitempty"`
	PowermonEnables          uint64 `protobuf:"varint,10,opt,name=powermon_enables,json=powermonEnables,proto3" json:"powermonEnables,omitempty"`
}

func (c *Config_PowerConfig) Reset() { *c = Config_PowerConfig{} }
func (c *Config_PowerConfig) ProtoMessage() {}

// NetworkConfig contains network settings.
type Config_NetworkConfig struct {
	WifiEnabled       bool   `protobuf:"varint,1,opt,name=wifi_enabled,json=wifiEnabled,proto3" json:"wifiEnabled,omitempty"`
	WifiSsid          string `protobuf:"bytes,3,opt,name=wifi_ssid,json=wifiSsid,proto3" json:"wifiSsid,omitempty"`
	WifiPsk           string `protobuf:"bytes,4,opt,name=wifi_psk,json=wifiPsk,proto3" json:"wifiPsk,omitempty"`
	NtpServer         string `protobuf:"bytes,5,opt,name=ntp_server,json=ntpServer,proto3" json:"ntpServer,omitempty"`
	EthEnabled        bool   `protobuf:"varint,6,opt,name=eth_enabled,json=ethEnabled,proto3" json:"ethEnabled,omitempty"`
	AddressMode       uint32 `protobuf:"varint,7,opt,name=address_mode,json=addressMode,proto3" json:"addressMode,omitempty"`
	Ipv4Config        *Config_NetworkConfig_IpV4Config `protobuf:"bytes,8,opt,name=ipv4_config,json=ipv4Config,proto3" json:"ipv4Config,omitempty"`
	RsyslogServer     string `protobuf:"bytes,9,opt,name=rsyslog_server,json=rsyslogServer,proto3" json:"rsyslogServer,omitempty"`
}

func (c *Config_NetworkConfig) Reset() { *c = Config_NetworkConfig{} }
func (c *Config_NetworkConfig) ProtoMessage() {}

// IpV4Config contains IPv4 settings.
type Config_NetworkConfig_IpV4Config struct {
	Ip      uint32 `protobuf:"fixed32,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Gateway uint32 `protobuf:"fixed32,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Subnet  uint32 `protobuf:"fixed32,3,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Dns     uint32 `protobuf:"fixed32,4,opt,name=dns,proto3" json:"dns,omitempty"`
}

func (c *Config_NetworkConfig_IpV4Config) Reset() { *c = Config_NetworkConfig_IpV4Config{} }
func (c *Config_NetworkConfig_IpV4Config) ProtoMessage() {}

// DisplayConfig contains display settings.
type Config_DisplayConfig struct {
	ScreenOnSecs       uint32 `protobuf:"varint,1,opt,name=screen_on_secs,json=screenOnSecs,proto3" json:"screenOnSecs,omitempty"`
	GpsFormat          uint32 `protobuf:"varint,2,opt,name=gps_format,json=gpsFormat,proto3" json:"gpsFormat,omitempty"`
	AutoScreenCarouselSecs uint32 `protobuf:"varint,3,opt,name=auto_screen_carousel_secs,json=autoScreenCarouselSecs,proto3" json:"autoScreenCarouselSecs,omitempty"`
	CompassNorthTop    bool   `protobuf:"varint,4,opt,name=compass_north_top,json=compassNorthTop,proto3" json:"compassNorthTop,omitempty"`
	FlipScreen         bool   `protobuf:"varint,5,opt,name=flip_screen,json=flipScreen,proto3" json:"flipScreen,omitempty"`
	Units              uint32 `protobuf:"varint,6,opt,name=units,proto3" json:"units,omitempty"`
	Oled               uint32 `protobuf:"varint,7,opt,name=oled,proto3" json:"oled,omitempty"`
	DisplayMode        uint32 `protobuf:"varint,8,opt,name=display_mode,json=displayMode,proto3" json:"displayMode,omitempty"`
	HeadingBold        bool   `protobuf:"varint,9,opt,name=heading_bold,json=headingBold,proto3" json:"headingBold,omitempty"`
	WakeOnTapOrMotion  bool   `protobuf:"varint,10,opt,name=wake_on_tap_or_motion,json=wakeOnTapOrMotion,proto3" json:"wakeOnTapOrMotion,omitempty"`
	CompassOrientation uint32 `protobuf:"varint,11,opt,name=compass_orientation,json=compassOrientation,proto3" json:"compassOrientation,omitempty"`
}

func (c *Config_DisplayConfig) Reset() { *c = Config_DisplayConfig{} }
func (c *Config_DisplayConfig) ProtoMessage() {}

// LoRaConfig contains LoRa radio settings.
type Config_LoRaConfig struct {
	UsePreset           bool                         `protobuf:"varint,1,opt,name=use_preset,json=usePreset,proto3" json:"usePreset,omitempty"`
	ModemPreset         uint32 `protobuf:"varint,2,opt,name=modem_preset,json=modemPreset,proto3,enum=meshtastic.Config_LoRaConfig_ModemPreset" json:"modemPreset,omitempty"`
	Bandwidth           uint32                       `protobuf:"varint,3,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	SpreadFactor        uint32                       `protobuf:"varint,4,opt,name=spread_factor,json=spreadFactor,proto3" json:"spreadFactor,omitempty"`
	CodingRate          uint32                       `protobuf:"varint,5,opt,name=coding_rate,json=codingRate,proto3" json:"codingRate,omitempty"`
	FrequencyOffset     float32                      `protobuf:"fixed32,6,opt,name=frequency_offset,json=frequencyOffset,proto3" json:"frequencyOffset,omitempty"`
	Region              uint32 `protobuf:"varint,7,opt,name=region,proto3,enum=meshtastic.Config_LoRaConfig_RegionCode" json:"region,omitempty"`
	HopLimit            uint32                       `protobuf:"varint,8,opt,name=hop_limit,json=hopLimit,proto3" json:"hopLimit,omitempty"`
	TxEnabled           bool                         `protobuf:"varint,9,opt,name=tx_enabled,json=txEnabled,proto3" json:"txEnabled,omitempty"`
	TxPower             int32                        `protobuf:"varint,10,opt,name=tx_power,json=txPower,proto3" json:"txPower,omitempty"`
	ChannelNum          uint32                       `protobuf:"varint,11,opt,name=channel_num,json=channelNum,proto3" json:"channelNum,omitempty"`
	OverrideDutyCycle   bool                         `protobuf:"varint,12,opt,name=override_duty_cycle,json=overrideDutyCycle,proto3" json:"overrideDutyCycle,omitempty"`
	Sx126xRxBoostedGain bool                         `protobuf:"varint,13,opt,name=sx126x_rx_boosted_gain,json=sx126xRxBoostedGain,proto3" json:"sx126xRxBoostedGain,omitempty"`
	OverrideFrequency   float32                      `protobuf:"fixed32,14,opt,name=override_frequency,json=overrideFrequency,proto3" json:"overrideFrequency,omitempty"`
	PaFanDisabled       bool                         `protobuf:"varint,15,opt,name=pa_fan_disabled,json=paFanDisabled,proto3" json:"paFanDisabled,omitempty"`
	IgnoreIncoming      []uint32                     `protobuf:"varint,103,rep,packed,name=ignore_incoming,json=ignoreIncoming,proto3" json:"ignoreIncoming,omitempty"`
	IgnoreMqtt          bool                         `protobuf:"varint,104,opt,name=ignore_mqtt,json=ignoreMqtt,proto3" json:"ignoreMqtt,omitempty"`
}

func (c *Config_LoRaConfig) Reset() { *c = Config_LoRaConfig{} }
func (c *Config_LoRaConfig) ProtoMessage() {}

// BluetoothConfig contains Bluetooth settings.
type Config_BluetoothConfig struct {
	Enabled     bool                               `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Mode        uint32 `protobuf:"varint,2,opt,name=mode,proto3,enum=meshtastic.Config_BluetoothConfig_PairingMode" json:"mode,omitempty"`
	FixedPin    uint32                             `protobuf:"varint,3,opt,name=fixed_pin,json=fixedPin,proto3" json:"fixedPin,omitempty"`
}

func (c *Config_BluetoothConfig) Reset() { *c = Config_BluetoothConfig{} }
func (c *Config_BluetoothConfig) ProtoMessage() {}

// SecurityConfig contains security settings.
type Config_SecurityConfig struct {
	PublicKey                []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey,omitempty"`
	PrivateKey               []byte `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"privateKey,omitempty"`
	AdminKey                 []byte `protobuf:"bytes,3,opt,name=admin_key,json=adminKey,proto3" json:"adminKey,omitempty"`
	IsManaged                bool   `protobuf:"varint,4,opt,name=is_managed,json=isManaged,proto3" json:"isManaged,omitempty"`
	SerialEnabled            bool   `protobuf:"varint,5,opt,name=serial_enabled,json=serialEnabled,proto3" json:"serialEnabled,omitempty"`
	DebugLogApiEnabled       bool   `protobuf:"varint,6,opt,name=debug_log_api_enabled,json=debugLogApiEnabled,proto3" json:"debugLogApiEnabled,omitempty"`
	AdminChannelEnabled      bool   `protobuf:"varint,8,opt,name=admin_channel_enabled,json=adminChannelEnabled,proto3" json:"adminChannelEnabled,omitempty"`
}

func (c *Config_SecurityConfig) Reset() { *c = Config_SecurityConfig{} }
func (c *Config_SecurityConfig) ProtoMessage() {}

// Config is the main configuration message.
type Config struct {
	// Types that are valid to be assigned to PayloadVariant:
	//	*Config_Device
	//	*Config_Position
	//	*Config_Power
	//	*Config_Network
	//	*Config_Display
	//	*Config_Lora
	//	*Config_Bluetooth
	//	*Config_Security
	PayloadVariant isConfig_PayloadVariant
}

type isConfig_PayloadVariant interface {
	isConfig_PayloadVariant()
}

type Config_Device struct {
	Device *Config_DeviceConfig
}

type Config_Position struct {
	Position *Config_PositionConfig
}

type Config_Power struct {
	Power *Config_PowerConfig
}

type Config_Network struct {
	Network *Config_NetworkConfig
}

type Config_Display struct {
	Display *Config_DisplayConfig
}

type Config_Lora struct {
	Lora *Config_LoRaConfig
}

type Config_Bluetooth struct {
	Bluetooth *Config_BluetoothConfig
}

type Config_Security struct {
	Security *Config_SecurityConfig
}

func (*Config_Device) isConfig_PayloadVariant()    {}
func (*Config_Position) isConfig_PayloadVariant()  {}
func (*Config_Power) isConfig_PayloadVariant()     {}
func (*Config_Network) isConfig_PayloadVariant()   {}
func (*Config_Display) isConfig_PayloadVariant()   {}
func (*Config_Lora) isConfig_PayloadVariant()      {}
func (*Config_Bluetooth) isConfig_PayloadVariant() {}
func (*Config_Security) isConfig_PayloadVariant()  {}

func (c *Config) GetDevice() *Config_DeviceConfig {
	if x, ok := c.PayloadVariant.(*Config_Device); ok {
		return x.Device
	}
	return nil
}

func (c *Config) GetPosition() *Config_PositionConfig {
	if x, ok := c.PayloadVariant.(*Config_Position); ok {
		return x.Position
	}
	return nil
}

func (c *Config) GetPower() *Config_PowerConfig {
	if x, ok := c.PayloadVariant.(*Config_Power); ok {
		return x.Power
	}
	return nil
}

func (c *Config) GetNetwork() *Config_NetworkConfig {
	if x, ok := c.PayloadVariant.(*Config_Network); ok {
		return x.Network
	}
	return nil
}

func (c *Config) GetDisplay() *Config_DisplayConfig {
	if x, ok := c.PayloadVariant.(*Config_Display); ok {
		return x.Display
	}
	return nil
}

func (c *Config) GetLora() *Config_LoRaConfig {
	if x, ok := c.PayloadVariant.(*Config_Lora); ok {
		return x.Lora
	}
	return nil
}

func (c *Config) GetBluetooth() *Config_BluetoothConfig {
	if x, ok := c.PayloadVariant.(*Config_Bluetooth); ok {
		return x.Bluetooth
	}
	return nil
}

func (c *Config) GetSecurity() *Config_SecurityConfig {
	if x, ok := c.PayloadVariant.(*Config_Security); ok {
		return x.Security
	}
	return nil
}

func (c *Config) Reset() { *c = Config{} }
func (c *Config) ProtoMessage() {}
