// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Source: meshtastic/mesh.proto

package pb

import (
	"google.golang.org/protobuf/encoding/protowire"
)

// HardwareModel represents the type of Meshtastic device hardware.
type HardwareModel int32

const (
	HardwareModel_UNSET                    HardwareModel = 0
	HardwareModel_TLORA_V2                 HardwareModel = 1
	HardwareModel_TLORA_V1                 HardwareModel = 2
	HardwareModel_TLORA_V2_1_1P6           HardwareModel = 3
	HardwareModel_TBEAM                    HardwareModel = 4
	HardwareModel_HELTEC_V2_0              HardwareModel = 5
	HardwareModel_TBEAM_V0P7               HardwareModel = 6
	HardwareModel_T_ECHO                   HardwareModel = 7
	HardwareModel_TLORA_V1_1P3             HardwareModel = 8
	HardwareModel_RAK4631                  HardwareModel = 9
	HardwareModel_HELTEC_V2_1              HardwareModel = 10
	HardwareModel_HELTEC_V1                HardwareModel = 11
	HardwareModel_LILYGO_TBEAM_S3_CORE     HardwareModel = 12
	HardwareModel_RAK11200                 HardwareModel = 13
	HardwareModel_NANO_G1                  HardwareModel = 14
	HardwareModel_TLORA_V2_1_1P8           HardwareModel = 15
	HardwareModel_TLORA_T3_S3              HardwareModel = 16
	HardwareModel_NANO_G1_EXPLORER         HardwareModel = 17
	HardwareModel_NANO_G2_ULTRA            HardwareModel = 18
	HardwareModel_LORA_TYPE                HardwareModel = 19
	HardwareModel_WIPHONE                  HardwareModel = 20
	HardwareModel_WIO_WM1110               HardwareModel = 21
	HardwareModel_RAK2560                  HardwareModel = 22
	HardwareModel_HELTEC_HRU_3601          HardwareModel = 23
	HardwareModel_HELTEC_WIRELESS_BRIDGE   HardwareModel = 24
	HardwareModel_STATION_G1               HardwareModel = 25
	HardwareModel_RAK11310                 HardwareModel = 26
	HardwareModel_SENSELORA_RP2040         HardwareModel = 27
	HardwareModel_SENSELORA_S3             HardwareModel = 28
	HardwareModel_CANARYONE                HardwareModel = 29
	HardwareModel_RP2040_LORA              HardwareModel = 30
	HardwareModel_STATION_G2               HardwareModel = 31
	HardwareModel_LORA_RELAY_V1            HardwareModel = 32
	HardwareModel_NRF52840DK               HardwareModel = 33
	HardwareModel_PPR                      HardwareModel = 34
	HardwareModel_GENIEBLOCKS              HardwareModel = 35
	HardwareModel_NRF52_UNKNOWN            HardwareModel = 36
	HardwareModel_PORTDUINO                HardwareModel = 37
	HardwareModel_ANDROID_SIM              HardwareModel = 38
	HardwareModel_DIY_V1                   HardwareModel = 39
	HardwareModel_NRF52840_PCA10059        HardwareModel = 40
	HardwareModel_DR_DEV                   HardwareModel = 41
	HardwareModel_M5STACK                  HardwareModel = 42
	HardwareModel_HELTEC_V3                HardwareModel = 43
	HardwareModel_HELTEC_WSL_V3            HardwareModel = 44
	HardwareModel_BETAFPV_2400_TX          HardwareModel = 45
	HardwareModel_BETAFPV_900_NANO_TX      HardwareModel = 46
	HardwareModel_RPI_PICO                 HardwareModel = 47
	HardwareModel_HELTEC_WIRELESS_TRACKER  HardwareModel = 48
	HardwareModel_HELTEC_WIRELESS_PAPER    HardwareModel = 49
	HardwareModel_T_DECK                   HardwareModel = 50
	HardwareModel_T_WATCH_S3               HardwareModel = 51
	HardwareModel_PICOMPUTER_S3            HardwareModel = 52
	HardwareModel_HELTEC_HT62              HardwareModel = 53
	HardwareModel_EBYTE_ESP32_S3           HardwareModel = 54
	HardwareModel_ESP32_S3_PICO            HardwareModel = 55
	HardwareModel_CHATTER_2                HardwareModel = 56
	HardwareModel_HELTEC_WIRELESS_PAPER_V1_0 HardwareModel = 57
	HardwareModel_HELTEC_WIRELESS_TRACKER_V1_0 HardwareModel = 58
	HardwareModel_UNPHONE                  HardwareModel = 59
	HardwareModel_TD_LORAC                 HardwareModel = 60
	HardwareModel_CDEBYTE_EORA_S3          HardwareModel = 61
	HardwareModel_TWC_MESH_V4              HardwareModel = 62
	HardwareModel_NRF52_PROMICRO_DIY       HardwareModel = 63
	HardwareModel_RADIOMASTER_900_BANDIT_NANO HardwareModel = 64
	HardwareModel_HELTEC_CAPSULE_SENSOR_V3 HardwareModel = 65
	HardwareModel_HELTEC_VISION_MASTER_T190 HardwareModel = 66
	HardwareModel_HELTEC_VISION_MASTER_E213 HardwareModel = 67
	HardwareModel_HELTEC_VISION_MASTER_E290 HardwareModel = 68
	HardwareModel_HELTEC_MESH_NODE_T114    HardwareModel = 69
	HardwareModel_SENSECAP_INDICATOR       HardwareModel = 70
	HardwareModel_TRACKER_T1000_E          HardwareModel = 71
	HardwareModel_RAK3172                  HardwareModel = 72
	HardwareModel_WIO_E5                   HardwareModel = 73
	HardwareModel_RADIOMASTER_900_BANDIT   HardwareModel = 74
	HardwareModel_ME25LS01_4Y10TD          HardwareModel = 75
	HardwareModel_RP2040_FEATHER_RFM95     HardwareModel = 76
	HardwareModel_M5STACK_COREBASIC        HardwareModel = 77
	HardwareModel_M5STACK_CORE2            HardwareModel = 78
	HardwareModel_RPI_PICO2                HardwareModel = 79
	HardwareModel_M5STACK_CORES3           HardwareModel = 80
	HardwareModel_SEEED_XIAO_S3            HardwareModel = 81
	HardwareModel_MS24SF1                  HardwareModel = 82
	HardwareModel_TLORA_C6                 HardwareModel = 83
	HardwareModel_WISMESH_TAP              HardwareModel = 84
	HardwareModel_ROUTASTIC                HardwareModel = 85
	HardwareModel_MESH_TAB                 HardwareModel = 86
	HardwareModel_MESHLINK                 HardwareModel = 87
	HardwareModel_XIAO_NRF52_KIT           HardwareModel = 88
	HardwareModel_THINKNODE_M1             HardwareModel = 89
	HardwareModel_THINKNODE_M2             HardwareModel = 90
	HardwareModel_T_ETH_ELITE              HardwareModel = 91
	HardwareModel_HELTEC_SENSOR_HUB        HardwareModel = 92
	HardwareModel_MUZI_BASE                HardwareModel = 93
	HardwareModel_HELTEC_MESH_POCKET       HardwareModel = 94
	HardwareModel_SEEED_SOLAR_NODE         HardwareModel = 95
	HardwareModel_NOMADSTAR_METEOR_PRO     HardwareModel = 96
	HardwareModel_CROWPANEL                HardwareModel = 97
	HardwareModel_LINK_32                  HardwareModel = 98
	HardwareModel_SEEED_WIO_TRACKER_L1     HardwareModel = 99
	HardwareModel_SEEED_WIO_TRACKER_L1_EINK HardwareModel = 100
	HardwareModel_MUZI_R1_NEO              HardwareModel = 101
	HardwareModel_T_DECK_PRO               HardwareModel = 102
	HardwareModel_T_LORA_PAGER             HardwareModel = 103
	HardwareModel_M5STACK_RESERVED         HardwareModel = 104
	HardwareModel_WISMESH_TAG              HardwareModel = 105
	HardwareModel_RAK3312                  HardwareModel = 106
	HardwareModel_THINKNODE_M5             HardwareModel = 107
	HardwareModel_HELTEC_MESH_SOLAR        HardwareModel = 108
	HardwareModel_T_ECHO_LITE              HardwareModel = 109
	HardwareModel_HELTEC_V4                HardwareModel = 110
	HardwareModel_M5STACK_C6L              HardwareModel = 111
	HardwareModel_M5STACK_CARDPUTER_ADV    HardwareModel = 112
	HardwareModel_HELTEC_WIRELESS_TRACKER_V2 HardwareModel = 113
	HardwareModel_T_WATCH_ULTRA            HardwareModel = 114
	HardwareModel_THINKNODE_M3             HardwareModel = 115
	HardwareModel_WISMESH_TAP_V2           HardwareModel = 116
	HardwareModel_RAK3401                  HardwareModel = 117
	HardwareModel_RAK6421                  HardwareModel = 118
	HardwareModel_THINKNODE_M4             HardwareModel = 119
	HardwareModel_THINKNODE_M6             HardwareModel = 120
	HardwareModel_MESHSTICK_1262           HardwareModel = 121
	HardwareModel_TBEAM_1_WATT             HardwareModel = 122
	HardwareModel_T5_S3_EPAPER_PRO         HardwareModel = 123
	HardwareModel_PRIVATE_HW               HardwareModel = 255
)

var HardwareModel_name = map[int32]string{
	0:   "UNSET",
	1:   "TLORA_V2",
	2:   "TLORA_V1",
	3:   "TLORA_V2_1_1P6",
	4:   "TBEAM",
	5:   "HELTEC_V2_0",
	6:   "TBEAM_V0P7",
	7:   "T_ECHO",
	8:   "TLORA_V1_1P3",
	9:   "RAK4631",
	10:  "HELTEC_V2_1",
	11:  "HELTEC_V1",
	12:  "LILYGO_TBEAM_S3_CORE",
	13:  "RAK11200",
	14:  "NANO_G1",
	15:  "TLORA_V2_1_1P8",
	16:  "TLORA_T3_S3",
	17:  "NANO_G1_EXPLORER",
	18:  "NANO_G2_ULTRA",
	19:  "LORA_TYPE",
	20:  "WIPHONE",
	21:  "WIO_WM1110",
	22:  "RAK2560",
	23:  "HELTEC_HRU_3601",
	24:  "HELTEC_WIRELESS_BRIDGE",
	25:  "STATION_G1",
	26:  "RAK11310",
	27:  "SENSELORA_RP2040",
	28:  "SENSELORA_S3",
	29:  "CANARYONE",
	30:  "RP2040_LORA",
	31:  "STATION_G2",
	32:  "LORA_RELAY_V1",
	33:  "NRF52840DK",
	34:  "PPR",
	35:  "GENIEBLOCKS",
	36:  "NRF52_UNKNOWN",
	37:  "PORTDUINO",
	38:  "ANDROID_SIM",
	39:  "DIY_V1",
	40:  "NRF52840_PCA10059",
	41:  "DR_DEV",
	42:  "M5STACK",
	43:  "HELTEC_V3",
	44:  "HELTEC_WSL_V3",
	45:  "BETAFPV_2400_TX",
	46:  "BETAFPV_900_NANO_TX",
	47:  "RPI_PICO",
	48:  "HELTEC_WIRELESS_TRACKER",
	49:  "HELTEC_WIRELESS_PAPER",
	50:  "T_DECK",
	51:  "T_WATCH_S3",
	52:  "PICOMPUTER_S3",
	53:  "HELTEC_HT62",
	54:  "EBYTE_ESP32_S3",
	55:  "ESP32_S3_PICO",
	56:  "CHATTER_2",
	57:  "HELTEC_WIRELESS_PAPER_V1_0",
	58:  "HELTEC_WIRELESS_TRACKER_V1_0",
	59:  "UNPHONE",
	60:  "TD_LORAC",
	61:  "CDEBYTE_EORA_S3",
	62:  "TWC_MESH_V4",
	63:  "NRF52_PROMICRO_DIY",
	64:  "RADIOMASTER_900_BANDIT_NANO",
	65:  "HELTEC_CAPSULE_SENSOR_V3",
	66:  "HELTEC_VISION_MASTER_T190",
	67:  "HELTEC_VISION_MASTER_E213",
	68:  "HELTEC_VISION_MASTER_E290",
	69:  "HELTEC_MESH_NODE_T114",
	70:  "SENSECAP_INDICATOR",
	71:  "TRACKER_T1000_E",
	72:  "RAK3172",
	73:  "WIO_E5",
	74:  "RADIOMASTER_900_BANDIT",
	75:  "ME25LS01_4Y10TD",
	76:  "RP2040_FEATHER_RFM95",
	77:  "M5STACK_COREBASIC",
	78:  "M5STACK_CORE2",
	79:  "RPI_PICO2",
	80:  "M5STACK_CORES3",
	81:  "SEEED_XIAO_S3",
	82:  "MS24SF1",
	83:  "TLORA_C6",
	84:  "WISMESH_TAP",
	85:  "ROUTASTIC",
	86:  "MESH_TAB",
	87:  "MESHLINK",
	88:  "XIAO_NRF52_KIT",
	89:  "THINKNODE_M1",
	90:  "THINKNODE_M2",
	91:  "T_ETH_ELITE",
	92:  "HELTEC_SENSOR_HUB",
	93:  "MUZI_BASE",
	94:  "HELTEC_MESH_POCKET",
	95:  "SEEED_SOLAR_NODE",
	96:  "NOMADSTAR_METEOR_PRO",
	97:  "CROWPANEL",
	98:  "LINK_32",
	99:  "SEEED_WIO_TRACKER_L1",
	100: "SEEED_WIO_TRACKER_L1_EINK",
	101: "MUZI_R1_NEO",
	102: "T_DECK_PRO",
	103: "T_LORA_PAGER",
	104: "M5STACK_RESERVED",
	105: "WISMESH_TAG",
	106: "RAK3312",
	107: "THINKNODE_M5",
	108: "HELTEC_MESH_SOLAR",
	109: "T_ECHO_LITE",
	110: "HELTEC_V4",
	111: "M5STACK_C6L",
	112: "M5STACK_CARDPUTER_ADV",
	113: "HELTEC_WIRELESS_TRACKER_V2",
	114: "T_WATCH_ULTRA",
	115: "THINKNODE_M3",
	116: "WISMESH_TAP_V2",
	117: "RAK3401",
	118: "RAK6421",
	119: "THINKNODE_M4",
	120: "THINKNODE_M6",
	121: "MESHSTICK_1262",
	122: "TBEAM_1_WATT",
	123: "T5_S3_EPAPER_PRO",
	255: "PRIVATE_HW",
}

func (x HardwareModel) String() string {
	if s, ok := HardwareModel_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// Priority defines the priority level for mesh packets.
type MeshPacket_Priority int32

const (
	MeshPacket_UNSET      MeshPacket_Priority = 0
	MeshPacket_MIN        MeshPacket_Priority = 1
	MeshPacket_BACKGROUND MeshPacket_Priority = 10
	MeshPacket_DEFAULT    MeshPacket_Priority = 64
	MeshPacket_RELIABLE   MeshPacket_Priority = 70
	MeshPacket_ACK        MeshPacket_Priority = 120
	MeshPacket_MAX        MeshPacket_Priority = 127
)

// Position represents GPS location data.
type Position struct {
	LatitudeI         int32  `protobuf:"sfixed32,1,opt,name=latitude_i,json=latitudeI,proto3" json:"latitudeI,omitempty"`
	LongitudeI        int32  `protobuf:"sfixed32,2,opt,name=longitude_i,json=longitudeI,proto3" json:"longitudeI,omitempty"`
	Altitude          int32  `protobuf:"varint,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Time              uint32 `protobuf:"fixed32,4,opt,name=time,proto3" json:"time,omitempty"`
	LocationSource    uint32 `protobuf:"varint,5,opt,name=location_source,json=locationSource,proto3" json:"locationSource,omitempty"`
	AltitudeSource    uint32 `protobuf:"varint,6,opt,name=altitude_source,json=altitudeSource,proto3" json:"altitudeSource,omitempty"`
	Timestamp         uint32 `protobuf:"fixed32,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TimestampMillisAdjust int32 `protobuf:"varint,8,opt,name=timestamp_millis_adjust,json=timestampMillisAdjust,proto3" json:"timestampMillisAdjust,omitempty"`
	AltitudeHae       int32  `protobuf:"sint32,9,opt,name=altitude_hae,json=altitudeHae,proto3" json:"altitudeHae,omitempty"`
	AltitudeGeoidalSeparation int32 `protobuf:"sint32,10,opt,name=altitude_geoidal_separation,json=altitudeGeoidalSeparation,proto3" json:"altitudeGeoidalSeparation,omitempty"`
	PDOP              uint32 `protobuf:"varint,11,opt,name=PDOP,proto3" json:"PDOP,omitempty"`
	HDOP              uint32 `protobuf:"varint,12,opt,name=HDOP,proto3" json:"HDOP,omitempty"`
	VDOP              uint32 `protobuf:"varint,13,opt,name=VDOP,proto3" json:"VDOP,omitempty"`
	GpsAccuracy       uint32 `protobuf:"varint,14,opt,name=gps_accuracy,json=gpsAccuracy,proto3" json:"gpsAccuracy,omitempty"`
	GroundSpeed       uint32 `protobuf:"varint,15,opt,name=ground_speed,json=groundSpeed,proto3" json:"groundSpeed,omitempty"`
	GroundTrack       uint32 `protobuf:"varint,16,opt,name=ground_track,json=groundTrack,proto3" json:"groundTrack,omitempty"`
	FixQuality        uint32 `protobuf:"varint,17,opt,name=fix_quality,json=fixQuality,proto3" json:"fixQuality,omitempty"`
	FixType           uint32 `protobuf:"varint,18,opt,name=fix_type,json=fixType,proto3" json:"fixType,omitempty"`
	SatsInView        uint32 `protobuf:"varint,19,opt,name=sats_in_view,json=satsInView,proto3" json:"satsInView,omitempty"`
	SensorId          uint32 `protobuf:"varint,20,opt,name=sensor_id,json=sensorId,proto3" json:"sensorId,omitempty"`
	NextUpdate        uint32 `protobuf:"varint,21,opt,name=next_update,json=nextUpdate,proto3" json:"nextUpdate,omitempty"`
	SeqNumber         uint32 `protobuf:"varint,22,opt,name=seq_number,json=seqNumber,proto3" json:"seqNumber,omitempty"`
	PrecisionBits     uint32 `protobuf:"varint,23,opt,name=precision_bits,json=precisionBits,proto3" json:"precisionBits,omitempty"`
}

func (p *Position) Reset() { *p = Position{} }
func (p *Position) ProtoMessage() {}

// Latitude returns the latitude as a float64 (degrees).
func (p *Position) Latitude() float64 {
	return float64(p.LatitudeI) * 1e-7
}

// Longitude returns the longitude as a float64 (degrees).
func (p *Position) Longitude() float64 {
	return float64(p.LongitudeI) * 1e-7
}

// SetLatitude sets the latitude from a float64 (degrees).
func (p *Position) SetLatitude(lat float64) {
	p.LatitudeI = int32(lat * 1e7)
}

// SetLongitude sets the longitude from a float64 (degrees).
func (p *Position) SetLongitude(lon float64) {
	p.LongitudeI = int32(lon * 1e7)
}

// User represents a user identity in the mesh.
type User struct {
	Id            string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LongName      string        `protobuf:"bytes,2,opt,name=long_name,json=longName,proto3" json:"longName,omitempty"`
	ShortName     string        `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"shortName,omitempty"`
	Macaddr       []byte        `protobuf:"bytes,4,opt,name=macaddr,proto3" json:"macaddr,omitempty"`
	HwModel       HardwareModel `protobuf:"varint,5,opt,name=hw_model,json=hwModel,proto3,enum=meshtastic.HardwareModel" json:"hwModel,omitempty"`
	IsLicensed    bool          `protobuf:"varint,6,opt,name=is_licensed,json=isLicensed,proto3" json:"isLicensed,omitempty"`
	Role          uint32        `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
	PublicKey     []byte        `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"publicKey,omitempty"`
}

func (u *User) Reset() { *u = User{} }
func (u *User) ProtoMessage() {}

// RouteDiscovery contains route tracing information.
type RouteDiscovery struct {
	Route     []uint32 `protobuf:"fixed32,1,rep,packed,name=route,proto3" json:"route,omitempty"`
	SnrTowards []int32 `protobuf:"zigzag32,2,rep,packed,name=snr_towards,json=snrTowards,proto3" json:"snrTowards,omitempty"`
	RouteBack []uint32 `protobuf:"fixed32,3,rep,packed,name=route_back,json=routeBack,proto3" json:"routeBack,omitempty"`
	SnrBack   []int32  `protobuf:"zigzag32,4,rep,packed,name=snr_back,json=snrBack,proto3" json:"snrBack,omitempty"`
}

func (r *RouteDiscovery) Reset() { *r = RouteDiscovery{} }
func (r *RouteDiscovery) ProtoMessage() {}

// Routing_Error represents routing error codes.
type Routing_Error int32

const (
	Routing_NONE               Routing_Error = 0
	Routing_NO_ROUTE           Routing_Error = 1
	Routing_GOT_NAK            Routing_Error = 2
	Routing_TIMEOUT            Routing_Error = 3
	Routing_NO_INTERFACE       Routing_Error = 4
	Routing_MAX_RETRANSMIT     Routing_Error = 5
	Routing_NO_CHANNEL         Routing_Error = 6
	Routing_TOO_LARGE          Routing_Error = 7
	Routing_NO_RESPONSE        Routing_Error = 8
	Routing_DUTY_CYCLE_LIMIT   Routing_Error = 9
	Routing_BAD_REQUEST        Routing_Error = 32
	Routing_NOT_AUTHORIZED     Routing_Error = 33
	Routing_PKI_FAILED         Routing_Error = 34
	Routing_PKI_UNKNOWN_PUBKEY Routing_Error = 35
)

var Routing_Error_name = map[int32]string{
	0:  "NONE",
	1:  "NO_ROUTE",
	2:  "GOT_NAK",
	3:  "TIMEOUT",
	4:  "NO_INTERFACE",
	5:  "MAX_RETRANSMIT",
	6:  "NO_CHANNEL",
	7:  "TOO_LARGE",
	8:  "NO_RESPONSE",
	9:  "DUTY_CYCLE_LIMIT",
	32: "BAD_REQUEST",
	33: "NOT_AUTHORIZED",
	34: "PKI_FAILED",
	35: "PKI_UNKNOWN_PUBKEY",
}

func (x Routing_Error) String() string {
	if s, ok := Routing_Error_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// Routing contains routing information for mesh packets.
type Routing struct {
	// Types that are valid to be assigned to Variant:
	//	*Routing_RouteRequest
	//	*Routing_RouteReply
	//	*Routing_ErrorReason
	Variant isRouting_Variant
}

type isRouting_Variant interface {
	isRouting_Variant()
}

type Routing_RouteRequest struct {
	RouteRequest *RouteDiscovery
}

type Routing_RouteReply struct {
	RouteReply *RouteDiscovery
}

type Routing_ErrorReason struct {
	ErrorReason Routing_Error
}

func (*Routing_RouteRequest) isRouting_Variant() {}
func (*Routing_RouteReply) isRouting_Variant()   {}
func (*Routing_ErrorReason) isRouting_Variant()  {}

func (r *Routing) GetRouteRequest() *RouteDiscovery {
	if x, ok := r.Variant.(*Routing_RouteRequest); ok {
		return x.RouteRequest
	}
	return nil
}

func (r *Routing) GetRouteReply() *RouteDiscovery {
	if x, ok := r.Variant.(*Routing_RouteReply); ok {
		return x.RouteReply
	}
	return nil
}

func (r *Routing) GetErrorReason() Routing_Error {
	if x, ok := r.Variant.(*Routing_ErrorReason); ok {
		return x.ErrorReason
	}
	return Routing_NONE
}

func (r *Routing) Reset() { *r = Routing{} }
func (r *Routing) ProtoMessage() {}

// Data is the payload portion of a mesh packet.
type Data struct {
	Portnum          PortNum `protobuf:"varint,1,opt,name=portnum,proto3,enum=meshtastic.PortNum" json:"portnum,omitempty"`
	Payload          []byte  `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	WantResponse     bool    `protobuf:"varint,3,opt,name=want_response,json=wantResponse,proto3" json:"wantResponse,omitempty"`
	Dest             uint32  `protobuf:"fixed32,4,opt,name=dest,proto3" json:"dest,omitempty"`
	Source           uint32  `protobuf:"fixed32,5,opt,name=source,proto3" json:"source,omitempty"`
	RequestId        uint32  `protobuf:"fixed32,6,opt,name=request_id,json=requestId,proto3" json:"requestId,omitempty"`
	ReplyId          uint32  `protobuf:"fixed32,7,opt,name=reply_id,json=replyId,proto3" json:"replyId,omitempty"`
	Emoji            uint32  `protobuf:"fixed32,8,opt,name=emoji,proto3" json:"emoji,omitempty"`
}

func (d *Data) Reset() { *d = Data{} }
func (d *Data) ProtoMessage() {}

// Waypoint represents a shareable location marker.
type Waypoint struct {
	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LatitudeI   int32  `protobuf:"sfixed32,2,opt,name=latitude_i,json=latitudeI,proto3" json:"latitudeI,omitempty"`
	LongitudeI  int32  `protobuf:"sfixed32,3,opt,name=longitude_i,json=longitudeI,proto3" json:"longitudeI,omitempty"`
	Expire      uint32 `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	LockedTo    uint32 `protobuf:"varint,5,opt,name=locked_to,json=lockedTo,proto3" json:"lockedTo,omitempty"`
	Name        string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Icon        uint32 `protobuf:"fixed32,8,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (w *Waypoint) Reset() { *w = Waypoint{} }
func (w *Waypoint) ProtoMessage() {}

// MeshPacket is the primary envelope for mesh messages.
type MeshPacket struct {
	From        uint32              `protobuf:"fixed32,1,opt,name=from,proto3" json:"from,omitempty"`
	To          uint32              `protobuf:"fixed32,2,opt,name=to,proto3" json:"to,omitempty"`
	Channel     uint32              `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// Types that are valid to be assigned to PayloadVariant:
	//	*MeshPacket_Decoded
	//	*MeshPacket_Encrypted
	PayloadVariant isMeshPacket_PayloadVariant
	Id             uint32              `protobuf:"fixed32,6,opt,name=id,proto3" json:"id,omitempty"`
	RxTime         uint32              `protobuf:"fixed32,7,opt,name=rx_time,json=rxTime,proto3" json:"rxTime,omitempty"`
	RxSnr          float32             `protobuf:"fixed32,8,opt,name=rx_snr,json=rxSnr,proto3" json:"rxSnr,omitempty"`
	HopLimit       uint32              `protobuf:"varint,9,opt,name=hop_limit,json=hopLimit,proto3" json:"hopLimit,omitempty"`
	WantAck        bool                `protobuf:"varint,10,opt,name=want_ack,json=wantAck,proto3" json:"wantAck,omitempty"`
	Priority       MeshPacket_Priority `protobuf:"varint,11,opt,name=priority,proto3,enum=meshtastic.MeshPacket_Priority" json:"priority,omitempty"`
	RxRssi         int32               `protobuf:"varint,12,opt,name=rx_rssi,json=rxRssi,proto3" json:"rxRssi,omitempty"`
	Delayed        uint32              `protobuf:"varint,13,opt,name=delayed,proto3" json:"delayed,omitempty"`
	ViaMqtt        bool                `protobuf:"varint,14,opt,name=via_mqtt,json=viaMqtt,proto3" json:"viaMqtt,omitempty"`
	HopStart       uint32              `protobuf:"varint,15,opt,name=hop_start,json=hopStart,proto3" json:"hopStart,omitempty"`
	PublicKey      []byte              `protobuf:"bytes,16,opt,name=public_key,json=publicKey,proto3" json:"publicKey,omitempty"`
	PkiEncrypted   bool                `protobuf:"varint,17,opt,name=pki_encrypted,json=pkiEncrypted,proto3" json:"pkiEncrypted,omitempty"`
}

type isMeshPacket_PayloadVariant interface {
	isMeshPacket_PayloadVariant()
}

type MeshPacket_Decoded struct {
	Decoded *Data
}

type MeshPacket_Encrypted struct {
	Encrypted []byte
}

func (*MeshPacket_Decoded) isMeshPacket_PayloadVariant()   {}
func (*MeshPacket_Encrypted) isMeshPacket_PayloadVariant() {}

func (m *MeshPacket) GetDecoded() *Data {
	if x, ok := m.PayloadVariant.(*MeshPacket_Decoded); ok {
		return x.Decoded
	}
	return nil
}

func (m *MeshPacket) GetEncrypted() []byte {
	if x, ok := m.PayloadVariant.(*MeshPacket_Encrypted); ok {
		return x.Encrypted
	}
	return nil
}

func (m *MeshPacket) Reset() { *m = MeshPacket{} }
func (m *MeshPacket) ProtoMessage() {}

// NodeInfo contains metadata about a mesh node.
type NodeInfo struct {
	Num           uint32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	User          *User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Position      *Position `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Snr           float32   `protobuf:"fixed32,4,opt,name=snr,proto3" json:"snr,omitempty"`
	LastHeard     uint32    `protobuf:"fixed32,5,opt,name=last_heard,json=lastHeard,proto3" json:"lastHeard,omitempty"`
	DeviceMetrics *DeviceMetrics `protobuf:"bytes,6,opt,name=device_metrics,json=deviceMetrics,proto3" json:"deviceMetrics,omitempty"`
	Channel       uint32    `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	ViaMqtt       bool      `protobuf:"varint,8,opt,name=via_mqtt,json=viaMqtt,proto3" json:"viaMqtt,omitempty"`
	Hops          uint32    `protobuf:"varint,9,opt,name=hops,proto3" json:"hops,omitempty"`
	IsFavorite    bool      `protobuf:"varint,10,opt,name=is_favorite,json=isFavorite,proto3" json:"isFavorite,omitempty"`
}

func (n *NodeInfo) Reset() { *n = NodeInfo{} }
func (n *NodeInfo) ProtoMessage() {}

// MyNodeInfo contains local debugging information.
type MyNodeInfo struct {
	MyNodeNum            uint32 `protobuf:"varint,1,opt,name=my_node_num,json=myNodeNum,proto3" json:"myNodeNum,omitempty"`
	RebootCount          uint32 `protobuf:"varint,8,opt,name=reboot_count,json=rebootCount,proto3" json:"rebootCount,omitempty"`
	MinAppVersion        uint32 `protobuf:"varint,11,opt,name=min_app_version,json=minAppVersion,proto3" json:"minAppVersion,omitempty"`
}

func (m *MyNodeInfo) Reset() { *m = MyNodeInfo{} }
func (m *MyNodeInfo) ProtoMessage() {}

// LogRecord represents a log message from the device.
type LogRecord struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Time    uint32 `protobuf:"fixed32,2,opt,name=time,proto3" json:"time,omitempty"`
	Source  string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Level   uint32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func (l *LogRecord) Reset() { *l = LogRecord{} }
func (l *LogRecord) ProtoMessage() {}

// QueueStatus contains information about the mesh packet queue.
type QueueStatus struct {
	Res       int32  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Free      uint32 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Maxlen    uint32 `protobuf:"varint,3,opt,name=maxlen,proto3" json:"maxlen,omitempty"`
	MeshPacketId uint32 `protobuf:"fixed32,4,opt,name=mesh_packet_id,json=meshPacketId,proto3" json:"meshPacketId,omitempty"`
}

func (q *QueueStatus) Reset() { *q = QueueStatus{} }
func (q *QueueStatus) ProtoMessage() {}

// FromRadio contains messages sent from the radio to the phone/PC.
type FromRadio struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to PayloadVariant:
	//	*FromRadio_Packet
	//	*FromRadio_MyInfo
	//	*FromRadio_NodeInfo
	//	*FromRadio_Config
	//	*FromRadio_LogRecord
	//	*FromRadio_ConfigCompleteId
	//	*FromRadio_Rebooted
	//	*FromRadio_ModuleConfig
	//	*FromRadio_Channel
	//	*FromRadio_QueueStatus
	//	*FromRadio_XmodemPacket
	//	*FromRadio_Metadata
	//	*FromRadio_MqttClientProxyMessage
	//	*FromRadio_FileInfo
	//	*FromRadio_ClientNotification
	PayloadVariant isFromRadio_PayloadVariant
}

type isFromRadio_PayloadVariant interface {
	isFromRadio_PayloadVariant()
}

type FromRadio_Packet struct {
	Packet *MeshPacket
}

type FromRadio_MyInfo struct {
	MyInfo *MyNodeInfo
}

type FromRadio_NodeInfo struct {
	NodeInfo *NodeInfo
}

type FromRadio_Config struct {
	Config *Config
}

type FromRadio_LogRecord struct {
	LogRecord *LogRecord
}

type FromRadio_ConfigCompleteId struct {
	ConfigCompleteId uint32
}

type FromRadio_Rebooted struct {
	Rebooted bool
}

type FromRadio_ModuleConfig struct {
	ModuleConfig *ModuleConfig
}

type FromRadio_Channel struct {
	Channel *Channel
}

type FromRadio_QueueStatus struct {
	QueueStatus *QueueStatus
}

type FromRadio_XmodemPacket struct {
	XmodemPacket []byte
}

type FromRadio_Metadata struct {
	Metadata *DeviceMetadata
}

type FromRadio_MqttClientProxyMessage struct {
	MqttClientProxyMessage *MqttClientProxyMessage
}

type FromRadio_FileInfo struct {
	FileInfo *FileInfo
}

type FromRadio_ClientNotification struct {
	ClientNotification *ClientNotification
}

func (*FromRadio_Packet) isFromRadio_PayloadVariant()                 {}
func (*FromRadio_MyInfo) isFromRadio_PayloadVariant()                 {}
func (*FromRadio_NodeInfo) isFromRadio_PayloadVariant()               {}
func (*FromRadio_Config) isFromRadio_PayloadVariant()                 {}
func (*FromRadio_LogRecord) isFromRadio_PayloadVariant()              {}
func (*FromRadio_ConfigCompleteId) isFromRadio_PayloadVariant()       {}
func (*FromRadio_Rebooted) isFromRadio_PayloadVariant()               {}
func (*FromRadio_ModuleConfig) isFromRadio_PayloadVariant()           {}
func (*FromRadio_Channel) isFromRadio_PayloadVariant()                {}
func (*FromRadio_QueueStatus) isFromRadio_PayloadVariant()            {}
func (*FromRadio_XmodemPacket) isFromRadio_PayloadVariant()           {}
func (*FromRadio_Metadata) isFromRadio_PayloadVariant()               {}
func (*FromRadio_MqttClientProxyMessage) isFromRadio_PayloadVariant() {}
func (*FromRadio_FileInfo) isFromRadio_PayloadVariant()               {}
func (*FromRadio_ClientNotification) isFromRadio_PayloadVariant()     {}

func (f *FromRadio) GetPacket() *MeshPacket {
	if x, ok := f.PayloadVariant.(*FromRadio_Packet); ok {
		return x.Packet
	}
	return nil
}

func (f *FromRadio) GetMyInfo() *MyNodeInfo {
	if x, ok := f.PayloadVariant.(*FromRadio_MyInfo); ok {
		return x.MyInfo
	}
	return nil
}

func (f *FromRadio) GetNodeInfo() *NodeInfo {
	if x, ok := f.PayloadVariant.(*FromRadio_NodeInfo); ok {
		return x.NodeInfo
	}
	return nil
}

func (f *FromRadio) GetConfig() *Config {
	if x, ok := f.PayloadVariant.(*FromRadio_Config); ok {
		return x.Config
	}
	return nil
}

func (f *FromRadio) GetLogRecord() *LogRecord {
	if x, ok := f.PayloadVariant.(*FromRadio_LogRecord); ok {
		return x.LogRecord
	}
	return nil
}

func (f *FromRadio) GetConfigCompleteId() uint32 {
	if x, ok := f.PayloadVariant.(*FromRadio_ConfigCompleteId); ok {
		return x.ConfigCompleteId
	}
	return 0
}

func (f *FromRadio) GetRebooted() bool {
	if x, ok := f.PayloadVariant.(*FromRadio_Rebooted); ok {
		return x.Rebooted
	}
	return false
}

func (f *FromRadio) GetModuleConfig() *ModuleConfig {
	if x, ok := f.PayloadVariant.(*FromRadio_ModuleConfig); ok {
		return x.ModuleConfig
	}
	return nil
}

func (f *FromRadio) GetChannel() *Channel {
	if x, ok := f.PayloadVariant.(*FromRadio_Channel); ok {
		return x.Channel
	}
	return nil
}

func (f *FromRadio) GetQueueStatus() *QueueStatus {
	if x, ok := f.PayloadVariant.(*FromRadio_QueueStatus); ok {
		return x.QueueStatus
	}
	return nil
}

func (f *FromRadio) GetMetadata() *DeviceMetadata {
	if x, ok := f.PayloadVariant.(*FromRadio_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (f *FromRadio) Reset() { *f = FromRadio{} }
func (f *FromRadio) ProtoMessage() {}

// ToRadio contains messages sent from the phone/PC to the radio.
type ToRadio struct {
	// Types that are valid to be assigned to PayloadVariant:
	//	*ToRadio_Packet
	//	*ToRadio_WantConfigId
	//	*ToRadio_Disconnect
	//	*ToRadio_XmodemPacket
	//	*ToRadio_MqttClientProxyMessage
	//	*ToRadio_Heartbeat
	PayloadVariant isToRadio_PayloadVariant
}

type isToRadio_PayloadVariant interface {
	isToRadio_PayloadVariant()
}

type ToRadio_Packet struct {
	Packet *MeshPacket
}

type ToRadio_WantConfigId struct {
	WantConfigId uint32
}

type ToRadio_Disconnect struct {
	Disconnect bool
}

type ToRadio_XmodemPacket struct {
	XmodemPacket []byte
}

type ToRadio_MqttClientProxyMessage struct {
	MqttClientProxyMessage *MqttClientProxyMessage
}

type ToRadio_Heartbeat struct {
	Heartbeat *Heartbeat
}

func (*ToRadio_Packet) isToRadio_PayloadVariant()                 {}
func (*ToRadio_WantConfigId) isToRadio_PayloadVariant()           {}
func (*ToRadio_Disconnect) isToRadio_PayloadVariant()             {}
func (*ToRadio_XmodemPacket) isToRadio_PayloadVariant()           {}
func (*ToRadio_MqttClientProxyMessage) isToRadio_PayloadVariant() {}
func (*ToRadio_Heartbeat) isToRadio_PayloadVariant()              {}

func (t *ToRadio) GetPacket() *MeshPacket {
	if x, ok := t.PayloadVariant.(*ToRadio_Packet); ok {
		return x.Packet
	}
	return nil
}

func (t *ToRadio) GetWantConfigId() uint32 {
	if x, ok := t.PayloadVariant.(*ToRadio_WantConfigId); ok {
		return x.WantConfigId
	}
	return 0
}

func (t *ToRadio) GetDisconnect() bool {
	if x, ok := t.PayloadVariant.(*ToRadio_Disconnect); ok {
		return x.Disconnect
	}
	return false
}

func (t *ToRadio) Reset() { *t = ToRadio{} }
func (t *ToRadio) ProtoMessage() {}

// Heartbeat is sent periodically to keep connection alive.
type Heartbeat struct{}

func (h *Heartbeat) Reset() { *h = Heartbeat{} }
func (h *Heartbeat) ProtoMessage() {}

// MqttClientProxyMessage is used for MQTT proxy communication.
type MqttClientProxyMessage struct {
	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Retained      bool   `protobuf:"varint,4,opt,name=retained,proto3" json:"retained,omitempty"`
}

func (m *MqttClientProxyMessage) Reset() { *m = MqttClientProxyMessage{} }
func (m *MqttClientProxyMessage) ProtoMessage() {}

// FileInfo contains file metadata.
type FileInfo struct {
	FileName  string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"fileName,omitempty"`
	SizeBytes uint32 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"sizeBytes,omitempty"`
}

func (f *FileInfo) Reset() { *f = FileInfo{} }
func (f *FileInfo) ProtoMessage() {}

// ClientNotification is sent from the device to notify the client.
type ClientNotification struct {
	ReplyId       uint32 `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"replyId,omitempty"`
	Time          uint32 `protobuf:"fixed32,2,opt,name=time,proto3" json:"time,omitempty"`
	Level         uint32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (c *ClientNotification) Reset() { *c = ClientNotification{} }
func (c *ClientNotification) ProtoMessage() {}

// DeviceMetadata contains device information.
type DeviceMetadata struct {
	FirmwareVersion    string        `protobuf:"bytes,1,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmwareVersion,omitempty"`
	DeviceStateVersion uint32        `protobuf:"varint,2,opt,name=device_state_version,json=deviceStateVersion,proto3" json:"deviceStateVersion,omitempty"`
	CanShutdown        bool          `protobuf:"varint,3,opt,name=can_shutdown,json=canShutdown,proto3" json:"canShutdown,omitempty"`
	HasWifi            bool          `protobuf:"varint,4,opt,name=has_wifi,json=hasWifi,proto3" json:"hasWifi,omitempty"`
	HasBluetooth       bool          `protobuf:"varint,5,opt,name=has_bluetooth,json=hasBluetooth,proto3" json:"hasBluetooth,omitempty"`
	HasEthernet        bool          `protobuf:"varint,6,opt,name=has_ethernet,json=hasEthernet,proto3" json:"hasEthernet,omitempty"`
	Role               uint32        `protobuf:"varint,7,opt,name=role,proto3" json:"role,omitempty"`
	PositionFlags      uint32        `protobuf:"varint,8,opt,name=position_flags,json=positionFlags,proto3" json:"positionFlags,omitempty"`
	HwModel            HardwareModel `protobuf:"varint,9,opt,name=hw_model,json=hwModel,proto3,enum=meshtastic.HardwareModel" json:"hwModel,omitempty"`
	HasRemoteHardware  bool          `protobuf:"varint,10,opt,name=has_remote_hardware,json=hasRemoteHardware,proto3" json:"hasRemoteHardware,omitempty"`
	HasPKC             bool          `protobuf:"varint,11,opt,name=has_pkc,json=hasPkc,proto3" json:"hasPkc,omitempty"`
}

func (d *DeviceMetadata) Reset() { *d = DeviceMetadata{} }
func (d *DeviceMetadata) ProtoMessage() {}

// Compressed is used for compressed payloads.
type Compressed struct {
	Portnum PortNum `protobuf:"varint,1,opt,name=portnum,proto3,enum=meshtastic.PortNum" json:"portnum,omitempty"`
	Data    []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (c *Compressed) Reset() { *c = Compressed{} }
func (c *Compressed) ProtoMessage() {}

// NeighborInfo contains information about mesh neighbors.
type NeighborInfo struct {
	NodeId               uint32      `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"nodeId,omitempty"`
	LastSentById         uint32      `protobuf:"varint,2,opt,name=last_sent_by_id,json=lastSentById,proto3" json:"lastSentById,omitempty"`
	NodeBroadcastIntervalSecs uint32 `protobuf:"varint,3,opt,name=node_broadcast_interval_secs,json=nodeBroadcastIntervalSecs,proto3" json:"nodeBroadcastIntervalSecs,omitempty"`
	Neighbors            []*Neighbor `protobuf:"bytes,4,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
}

func (n *NeighborInfo) Reset() { *n = NeighborInfo{} }
func (n *NeighborInfo) ProtoMessage() {}

// Neighbor represents a single mesh neighbor.
type Neighbor struct {
	NodeId   uint32  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"nodeId,omitempty"`
	Snr      float32 `protobuf:"fixed32,2,opt,name=snr,proto3" json:"snr,omitempty"`
	LastRxTime uint32 `protobuf:"fixed32,3,opt,name=last_rx_time,json=lastRxTime,proto3" json:"lastRxTime,omitempty"`
	NodeBroadcastIntervalSecs uint32 `protobuf:"varint,4,opt,name=node_broadcast_interval_secs,json=nodeBroadcastIntervalSecs,proto3" json:"nodeBroadcastIntervalSecs,omitempty"`
}

func (n *Neighbor) Reset() { *n = Neighbor{} }
func (n *Neighbor) ProtoMessage() {}

// Helper functions for protobuf serialization

// MarshalFromRadio encodes a FromRadio message to protobuf wire format.
func MarshalFromRadio(f *FromRadio) ([]byte, error) {
	var buf []byte

	// Field 1: id (varint)
	if f.Id != 0 {
		buf = protowire.AppendTag(buf, 1, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(f.Id))
	}

	// Handle payload variant based on type
	switch v := f.PayloadVariant.(type) {
	case *FromRadio_Packet:
		if v.Packet != nil {
			data, err := marshalMeshPacketBasic(v.Packet)
			if err != nil {
				return nil, err
			}
			buf = protowire.AppendTag(buf, 2, protowire.BytesType)
			buf = protowire.AppendBytes(buf, data)
		}
	case *FromRadio_MyInfo:
		// Field 3: my_info
		if v.MyInfo != nil {
			data, err := marshalMyNodeInfo(v.MyInfo)
			if err != nil {
				return nil, err
			}
			buf = protowire.AppendTag(buf, 3, protowire.BytesType)
			buf = protowire.AppendBytes(buf, data)
		}
	case *FromRadio_NodeInfo:
		// Field 4: node_info
		if v.NodeInfo != nil {
			data, err := marshalNodeInfo(v.NodeInfo)
			if err != nil {
				return nil, err
			}
			buf = protowire.AppendTag(buf, 4, protowire.BytesType)
			buf = protowire.AppendBytes(buf, data)
		}
	case *FromRadio_ConfigCompleteId:
		// Field 6: config_complete_id
		buf = protowire.AppendTag(buf, 6, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(v.ConfigCompleteId))
	case *FromRadio_Rebooted:
		// Field 7: rebooted
		buf = protowire.AppendTag(buf, 7, protowire.VarintType)
		if v.Rebooted {
			buf = protowire.AppendVarint(buf, 1)
		} else {
			buf = protowire.AppendVarint(buf, 0)
		}
	}

	return buf, nil
}

func marshalMeshPacketBasic(p *MeshPacket) ([]byte, error) {
	var buf []byte
	if p.From != 0 {
		buf = protowire.AppendTag(buf, 1, protowire.Fixed32Type)
		buf = protowire.AppendFixed32(buf, p.From)
	}
	if p.To != 0 {
		buf = protowire.AppendTag(buf, 2, protowire.Fixed32Type)
		buf = protowire.AppendFixed32(buf, p.To)
	}
	if p.Channel != 0 {
		buf = protowire.AppendTag(buf, 3, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(p.Channel))
	}
	if p.Id != 0 {
		buf = protowire.AppendTag(buf, 6, protowire.Fixed32Type)
		buf = protowire.AppendFixed32(buf, p.Id)
	}
	if p.HopLimit != 0 {
		buf = protowire.AppendTag(buf, 9, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(p.HopLimit))
	}
	return buf, nil
}

func marshalMyNodeInfo(m *MyNodeInfo) ([]byte, error) {
	var buf []byte
	if m.MyNodeNum != 0 {
		buf = protowire.AppendTag(buf, 1, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(m.MyNodeNum))
	}
	if m.RebootCount != 0 {
		buf = protowire.AppendTag(buf, 8, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(m.RebootCount))
	}
	if m.MinAppVersion != 0 {
		buf = protowire.AppendTag(buf, 11, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(m.MinAppVersion))
	}
	return buf, nil
}

func marshalNodeInfo(n *NodeInfo) ([]byte, error) {
	var buf []byte
	if n.Num != 0 {
		buf = protowire.AppendTag(buf, 1, protowire.VarintType)
		buf = protowire.AppendVarint(buf, uint64(n.Num))
	}
	// Additional fields would be marshaled here
	return buf, nil
}

// ServiceEnvelope is used to wrap MeshPackets for MQTT transmission.
// This allows MQTT gateways to pass along packets from the mesh.
type ServiceEnvelope struct {
	Packet    *MeshPacket `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	ChannelId string      `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channelId,omitempty"`
	GatewayId string      `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gatewayId,omitempty"`
}

func (s *ServiceEnvelope) Reset() { *s = ServiceEnvelope{} }
func (s *ServiceEnvelope) ProtoMessage() {}
