// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Source: meshtastic/portnums.proto

package pb

// PortNum defines the port number used for application routing in Meshtastic.
// Port ranges:
//   0-63: Core Meshtastic use
//   64-127: Registered 3rd party apps
//   256-511: Private applications
type PortNum int32

const (
	PortNum_UNKNOWN_APP             PortNum = 0
	PortNum_TEXT_MESSAGE_APP        PortNum = 1
	PortNum_REMOTE_HARDWARE_APP     PortNum = 2
	PortNum_POSITION_APP            PortNum = 3
	PortNum_NODEINFO_APP            PortNum = 4
	PortNum_ROUTING_APP             PortNum = 5
	PortNum_ADMIN_APP               PortNum = 6
	PortNum_TEXT_MESSAGE_COMPRESSED_APP PortNum = 7
	PortNum_WAYPOINT_APP            PortNum = 8
	PortNum_AUDIO_APP               PortNum = 9
	PortNum_DETECTION_SENSOR_APP    PortNum = 10
	PortNum_REPLY_APP               PortNum = 32
	PortNum_IP_TUNNEL_APP           PortNum = 33
	PortNum_PAXCOUNTER_APP          PortNum = 34
	PortNum_SERIAL_APP              PortNum = 64
	PortNum_STORE_FORWARD_APP       PortNum = 65
	PortNum_RANGE_TEST_APP          PortNum = 66
	PortNum_TELEMETRY_APP           PortNum = 67
	PortNum_ZPS_APP                 PortNum = 68
	PortNum_SIMULATOR_APP           PortNum = 69
	PortNum_TRACEROUTE_APP          PortNum = 70
	PortNum_NEIGHBORINFO_APP        PortNum = 71
	PortNum_ATAK_PLUGIN             PortNum = 72
	PortNum_MAP_REPORT_APP          PortNum = 73
	PortNum_POWERSTRESS_APP         PortNum = 74
	PortNum_PRIVATE_APP             PortNum = 256
	PortNum_ATAK_FORWARDER          PortNum = 257
	PortNum_MAX                     PortNum = 511
)

var PortNum_name = map[int32]string{
	0:   "UNKNOWN_APP",
	1:   "TEXT_MESSAGE_APP",
	2:   "REMOTE_HARDWARE_APP",
	3:   "POSITION_APP",
	4:   "NODEINFO_APP",
	5:   "ROUTING_APP",
	6:   "ADMIN_APP",
	7:   "TEXT_MESSAGE_COMPRESSED_APP",
	8:   "WAYPOINT_APP",
	9:   "AUDIO_APP",
	10:  "DETECTION_SENSOR_APP",
	32:  "REPLY_APP",
	33:  "IP_TUNNEL_APP",
	34:  "PAXCOUNTER_APP",
	64:  "SERIAL_APP",
	65:  "STORE_FORWARD_APP",
	66:  "RANGE_TEST_APP",
	67:  "TELEMETRY_APP",
	68:  "ZPS_APP",
	69:  "SIMULATOR_APP",
	70:  "TRACEROUTE_APP",
	71:  "NEIGHBORINFO_APP",
	72:  "ATAK_PLUGIN",
	73:  "MAP_REPORT_APP",
	74:  "POWERSTRESS_APP",
	256: "PRIVATE_APP",
	257: "ATAK_FORWARDER",
	511: "MAX",
}

var PortNum_value = map[string]int32{
	"UNKNOWN_APP":                 0,
	"TEXT_MESSAGE_APP":            1,
	"REMOTE_HARDWARE_APP":         2,
	"POSITION_APP":                3,
	"NODEINFO_APP":                4,
	"ROUTING_APP":                 5,
	"ADMIN_APP":                   6,
	"TEXT_MESSAGE_COMPRESSED_APP": 7,
	"WAYPOINT_APP":                8,
	"AUDIO_APP":                   9,
	"DETECTION_SENSOR_APP":        10,
	"REPLY_APP":                   32,
	"IP_TUNNEL_APP":               33,
	"PAXCOUNTER_APP":              34,
	"SERIAL_APP":                  64,
	"STORE_FORWARD_APP":           65,
	"RANGE_TEST_APP":              66,
	"TELEMETRY_APP":               67,
	"ZPS_APP":                     68,
	"SIMULATOR_APP":               69,
	"TRACEROUTE_APP":              70,
	"NEIGHBORINFO_APP":            71,
	"ATAK_PLUGIN":                 72,
	"MAP_REPORT_APP":              73,
	"POWERSTRESS_APP":             74,
	"PRIVATE_APP":                 256,
	"ATAK_FORWARDER":              257,
	"MAX":                         511,
}

func (x PortNum) String() string {
	if s, ok := PortNum_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

func (x PortNum) Number() int32 {
	return int32(x)
}
