// Code generated by hand from meshtastic protobufs. DO NOT EDIT.
// Source: meshtastic/telemetry.proto

package pb

import "unsafe"

// TelemetrySensorType identifies the type of sensor.
type TelemetrySensorType int32

const (
	TelemetrySensorType_SENSOR_UNSET     TelemetrySensorType = 0
	TelemetrySensorType_BME280           TelemetrySensorType = 1
	TelemetrySensorType_BME680           TelemetrySensorType = 2
	TelemetrySensorType_MCP9808          TelemetrySensorType = 3
	TelemetrySensorType_INA260           TelemetrySensorType = 4
	TelemetrySensorType_INA219           TelemetrySensorType = 5
	TelemetrySensorType_BMP280           TelemetrySensorType = 6
	TelemetrySensorType_SHTC3            TelemetrySensorType = 7
	TelemetrySensorType_LPS22            TelemetrySensorType = 8
	TelemetrySensorType_QMC6310          TelemetrySensorType = 9
	TelemetrySensorType_QMI8658          TelemetrySensorType = 10
	TelemetrySensorType_QMC5883L         TelemetrySensorType = 11
	TelemetrySensorType_SHT31            TelemetrySensorType = 12
	TelemetrySensorType_PMSA003I         TelemetrySensorType = 13
	TelemetrySensorType_INA3221          TelemetrySensorType = 14
	TelemetrySensorType_BMP085           TelemetrySensorType = 15
	TelemetrySensorType_RCWL9620         TelemetrySensorType = 16
	TelemetrySensorType_SHT4X            TelemetrySensorType = 17
	TelemetrySensorType_VEML7700         TelemetrySensorType = 18
	TelemetrySensorType_MLX90632         TelemetrySensorType = 19
	TelemetrySensorType_OPT3001          TelemetrySensorType = 20
	TelemetrySensorType_LTR390UV         TelemetrySensorType = 21
	TelemetrySensorType_TSL25911FN       TelemetrySensorType = 22
	TelemetrySensorType_AHT10            TelemetrySensorType = 23
	TelemetrySensorType_DFROBOT_LARK     TelemetrySensorType = 24
	TelemetrySensorType_NAU7802          TelemetrySensorType = 25
	TelemetrySensorType_BMP3XX           TelemetrySensorType = 26
	TelemetrySensorType_ICM20948         TelemetrySensorType = 27
	TelemetrySensorType_MAX17048         TelemetrySensorType = 28
	TelemetrySensorType_CUSTOM_SENSOR    TelemetrySensorType = 29
	TelemetrySensorType_MAX30102         TelemetrySensorType = 30
	TelemetrySensorType_MLX90614         TelemetrySensorType = 31
	TelemetrySensorType_SCD4X            TelemetrySensorType = 32
	TelemetrySensorType_RADSENS          TelemetrySensorType = 33
	TelemetrySensorType_INA226           TelemetrySensorType = 34
	TelemetrySensorType_VEML6075         TelemetrySensorType = 35
	TelemetrySensorType_SEN5X            TelemetrySensorType = 36
	TelemetrySensorType_HMC5883L         TelemetrySensorType = 37
	TelemetrySensorType_DFROBOT_RAIN     TelemetrySensorType = 38
	TelemetrySensorType_DS18B20          TelemetrySensorType = 39
	TelemetrySensorType_AGS02MA          TelemetrySensorType = 40
	TelemetrySensorType_SCD30            TelemetrySensorType = 41
	TelemetrySensorType_ENS160           TelemetrySensorType = 42
	TelemetrySensorType_LPS25HB          TelemetrySensorType = 43
	TelemetrySensorType_SHT20            TelemetrySensorType = 44
	TelemetrySensorType_SHT40            TelemetrySensorType = 45
)

var TelemetrySensorType_name = map[int32]string{
	0:  "SENSOR_UNSET",
	1:  "BME280",
	2:  "BME680",
	3:  "MCP9808",
	4:  "INA260",
	5:  "INA219",
	6:  "BMP280",
	7:  "SHTC3",
	8:  "LPS22",
	9:  "QMC6310",
	10: "QMI8658",
	11: "QMC5883L",
	12: "SHT31",
	13: "PMSA003I",
	14: "INA3221",
	15: "BMP085",
	16: "RCWL9620",
	17: "SHT4X",
	18: "VEML7700",
	19: "MLX90632",
	20: "OPT3001",
	21: "LTR390UV",
	22: "TSL25911FN",
	23: "AHT10",
	24: "DFROBOT_LARK",
	25: "NAU7802",
	26: "BMP3XX",
	27: "ICM20948",
	28: "MAX17048",
	29: "CUSTOM_SENSOR",
	30: "MAX30102",
	31: "MLX90614",
	32: "SCD4X",
	33: "RADSENS",
	34: "INA226",
	35: "VEML6075",
	36: "SEN5X",
	37: "HMC5883L",
	38: "DFROBOT_RAIN",
	39: "DS18B20",
	40: "AGS02MA",
	41: "SCD30",
	42: "ENS160",
	43: "LPS25HB",
	44: "SHT20",
	45: "SHT40",
}

func (x TelemetrySensorType) String() string {
	if s, ok := TelemetrySensorType_name[int32(x)]; ok {
		return s
	}
	return "UNKNOWN"
}

// DeviceMetrics contains device telemetry data.
type DeviceMetrics struct {
	BatteryLevel       uint32  `protobuf:"varint,1,opt,name=battery_level,json=batteryLevel,proto3" json:"batteryLevel,omitempty"`
	Voltage            float32 `protobuf:"fixed32,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	ChannelUtilization float32 `protobuf:"fixed32,3,opt,name=channel_utilization,json=channelUtilization,proto3" json:"channelUtilization,omitempty"`
	AirUtilTx          float32 `protobuf:"fixed32,4,opt,name=air_util_tx,json=airUtilTx,proto3" json:"airUtilTx,omitempty"`
	UptimeSeconds      uint32  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptimeSeconds,omitempty"`
}

func (d *DeviceMetrics) Reset() { *d = DeviceMetrics{} }
func (d *DeviceMetrics) ProtoMessage() {}

// EnvironmentMetrics contains environmental sensor data.
type EnvironmentMetrics struct {
	Temperature         float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	RelativeHumidity    float32 `protobuf:"fixed32,2,opt,name=relative_humidity,json=relativeHumidity,proto3" json:"relativeHumidity,omitempty"`
	BarometricPressure  float32 `protobuf:"fixed32,3,opt,name=barometric_pressure,json=barometricPressure,proto3" json:"barometricPressure,omitempty"`
	GasResistance       float32 `protobuf:"fixed32,4,opt,name=gas_resistance,json=gasResistance,proto3" json:"gasResistance,omitempty"`
	Voltage             float32 `protobuf:"fixed32,5,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current             float32 `protobuf:"fixed32,6,opt,name=current,proto3" json:"current,omitempty"`
	Iaq                 uint32  `protobuf:"varint,7,opt,name=iaq,proto3" json:"iaq,omitempty"`
	Distance            float32 `protobuf:"fixed32,8,opt,name=distance,proto3" json:"distance,omitempty"`
	Lux                 float32 `protobuf:"fixed32,9,opt,name=lux,proto3" json:"lux,omitempty"`
	WhiteLux            float32 `protobuf:"fixed32,10,opt,name=white_lux,json=whiteLux,proto3" json:"whiteLux,omitempty"`
	IrLux               float32 `protobuf:"fixed32,11,opt,name=ir_lux,json=irLux,proto3" json:"irLux,omitempty"`
	UvLux               float32 `protobuf:"fixed32,12,opt,name=uv_lux,json=uvLux,proto3" json:"uvLux,omitempty"`
	WindDirection       uint32  `protobuf:"varint,13,opt,name=wind_direction,json=windDirection,proto3" json:"windDirection,omitempty"`
	WindSpeed           float32 `protobuf:"fixed32,14,opt,name=wind_speed,json=windSpeed,proto3" json:"windSpeed,omitempty"`
	Weight              float32 `protobuf:"fixed32,15,opt,name=weight,proto3" json:"weight,omitempty"`
	WindGust            float32 `protobuf:"fixed32,16,opt,name=wind_gust,json=windGust,proto3" json:"windGust,omitempty"`
	WindLull            float32 `protobuf:"fixed32,17,opt,name=wind_lull,json=windLull,proto3" json:"windLull,omitempty"`
	Radiation           float32 `protobuf:"fixed32,18,opt,name=radiation,proto3" json:"radiation,omitempty"`
	Rainfall            float32 `protobuf:"fixed32,19,opt,name=rainfall,proto3" json:"rainfall,omitempty"`
	SoilMoisture        float32 `protobuf:"fixed32,20,opt,name=soil_moisture,json=soilMoisture,proto3" json:"soilMoisture,omitempty"`
	SoilTemperature     float32 `protobuf:"fixed32,21,opt,name=soil_temperature,json=soilTemperature,proto3" json:"soilTemperature,omitempty"`
}

func (e *EnvironmentMetrics) Reset() { *e = EnvironmentMetrics{} }
func (e *EnvironmentMetrics) ProtoMessage() {}

// PowerMetrics contains power monitoring data.
type PowerMetrics struct {
	Ch1Voltage float32 `protobuf:"fixed32,1,opt,name=ch1_voltage,json=ch1Voltage,proto3" json:"ch1Voltage,omitempty"`
	Ch1Current float32 `protobuf:"fixed32,2,opt,name=ch1_current,json=ch1Current,proto3" json:"ch1Current,omitempty"`
	Ch2Voltage float32 `protobuf:"fixed32,3,opt,name=ch2_voltage,json=ch2Voltage,proto3" json:"ch2Voltage,omitempty"`
	Ch2Current float32 `protobuf:"fixed32,4,opt,name=ch2_current,json=ch2Current,proto3" json:"ch2Current,omitempty"`
	Ch3Voltage float32 `protobuf:"fixed32,5,opt,name=ch3_voltage,json=ch3Voltage,proto3" json:"ch3Voltage,omitempty"`
	Ch3Current float32 `protobuf:"fixed32,6,opt,name=ch3_current,json=ch3Current,proto3" json:"ch3Current,omitempty"`
}

func (p *PowerMetrics) Reset() { *p = PowerMetrics{} }
func (p *PowerMetrics) ProtoMessage() {}

// AirQualityMetrics contains air quality sensor data.
type AirQualityMetrics struct {
	Pm10Standard  uint32 `protobuf:"varint,1,opt,name=pm10_standard,json=pm10Standard,proto3" json:"pm10Standard,omitempty"`
	Pm25Standard  uint32 `protobuf:"varint,2,opt,name=pm25_standard,json=pm25Standard,proto3" json:"pm25Standard,omitempty"`
	Pm100Standard uint32 `protobuf:"varint,3,opt,name=pm100_standard,json=pm100Standard,proto3" json:"pm100Standard,omitempty"`
	Pm10Environmental  uint32 `protobuf:"varint,4,opt,name=pm10_environmental,json=pm10Environmental,proto3" json:"pm10Environmental,omitempty"`
	Pm25Environmental  uint32 `protobuf:"varint,5,opt,name=pm25_environmental,json=pm25Environmental,proto3" json:"pm25Environmental,omitempty"`
	Pm100Environmental uint32 `protobuf:"varint,6,opt,name=pm100_environmental,json=pm100Environmental,proto3" json:"pm100Environmental,omitempty"`
	Particles03um uint32 `protobuf:"varint,7,opt,name=particles_03um,json=particles03um,proto3" json:"particles03um,omitempty"`
	Particles05um uint32 `protobuf:"varint,8,opt,name=particles_05um,json=particles05um,proto3" json:"particles05um,omitempty"`
	Particles10um uint32 `protobuf:"varint,9,opt,name=particles_10um,json=particles10um,proto3" json:"particles10um,omitempty"`
	Particles25um uint32 `protobuf:"varint,10,opt,name=particles_25um,json=particles25um,proto3" json:"particles25um,omitempty"`
	Particles50um uint32 `protobuf:"varint,11,opt,name=particles_50um,json=particles50um,proto3" json:"particles50um,omitempty"`
	Particles100um uint32 `protobuf:"varint,12,opt,name=particles_100um,json=particles100um,proto3" json:"particles100um,omitempty"`
	Co2           uint32 `protobuf:"varint,13,opt,name=co2,proto3" json:"co2,omitempty"`
}

func (a *AirQualityMetrics) Reset() { *a = AirQualityMetrics{} }
func (a *AirQualityMetrics) ProtoMessage() {}

// LocalStats contains local device statistics.
type LocalStats struct {
	UptimeSeconds        uint32 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptimeSeconds,omitempty"`
	ChannelUtilization   float32 `protobuf:"fixed32,2,opt,name=channel_utilization,json=channelUtilization,proto3" json:"channelUtilization,omitempty"`
	AirUtilTx            float32 `protobuf:"fixed32,3,opt,name=air_util_tx,json=airUtilTx,proto3" json:"airUtilTx,omitempty"`
	NumPacketsTx         uint32 `protobuf:"varint,4,opt,name=num_packets_tx,json=numPacketsTx,proto3" json:"numPacketsTx,omitempty"`
	NumPacketsRx         uint32 `protobuf:"varint,5,opt,name=num_packets_rx,json=numPacketsRx,proto3" json:"numPacketsRx,omitempty"`
	NumPacketsRxBad      uint32 `protobuf:"varint,6,opt,name=num_packets_rx_bad,json=numPacketsRxBad,proto3" json:"numPacketsRxBad,omitempty"`
	NumOnlineNodes       uint32 `protobuf:"varint,7,opt,name=num_online_nodes,json=numOnlineNodes,proto3" json:"numOnlineNodes,omitempty"`
	NumTotalNodes        uint32 `protobuf:"varint,8,opt,name=num_total_nodes,json=numTotalNodes,proto3" json:"numTotalNodes,omitempty"`
	NumRxDupe            uint32 `protobuf:"varint,9,opt,name=num_rx_dupe,json=numRxDupe,proto3" json:"numRxDupe,omitempty"`
	NumTxRelay           uint32 `protobuf:"varint,10,opt,name=num_tx_relay,json=numTxRelay,proto3" json:"numTxRelay,omitempty"`
	NumTxRelayCanceled   uint32 `protobuf:"varint,11,opt,name=num_tx_relay_canceled,json=numTxRelayCanceled,proto3" json:"numTxRelayCanceled,omitempty"`
}

func (l *LocalStats) Reset() { *l = LocalStats{} }
func (l *LocalStats) ProtoMessage() {}

// HealthMetrics contains health telemetry data.
type HealthMetrics struct {
	HeartBpm         uint32  `protobuf:"varint,1,opt,name=heart_bpm,json=heartBpm,proto3" json:"heartBpm,omitempty"`
	Spout            uint32  `protobuf:"varint,2,opt,name=spout,proto3" json:"spout,omitempty"`
	Temperature      float32 `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (h *HealthMetrics) Reset() { *h = HealthMetrics{} }
func (h *HealthMetrics) ProtoMessage() {}

// Telemetry is the main telemetry message envelope.
type Telemetry struct {
	Time uint32 `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Variant:
	//	*Telemetry_DeviceMetrics
	//	*Telemetry_EnvironmentMetrics
	//	*Telemetry_AirQualityMetrics
	//	*Telemetry_PowerMetrics
	//	*Telemetry_LocalStats
	//	*Telemetry_HealthMetrics
	Variant isTelemetry_Variant
}

type isTelemetry_Variant interface {
	isTelemetry_Variant()
}

type Telemetry_DeviceMetrics struct {
	DeviceMetrics *DeviceMetrics
}

type Telemetry_EnvironmentMetrics struct {
	EnvironmentMetrics *EnvironmentMetrics
}

type Telemetry_AirQualityMetrics struct {
	AirQualityMetrics *AirQualityMetrics
}

type Telemetry_PowerMetrics struct {
	PowerMetrics *PowerMetrics
}

type Telemetry_LocalStats struct {
	LocalStats *LocalStats
}

type Telemetry_HealthMetrics struct {
	HealthMetrics *HealthMetrics
}

func (*Telemetry_DeviceMetrics) isTelemetry_Variant()       {}
func (*Telemetry_EnvironmentMetrics) isTelemetry_Variant()  {}
func (*Telemetry_AirQualityMetrics) isTelemetry_Variant()   {}
func (*Telemetry_PowerMetrics) isTelemetry_Variant()        {}
func (*Telemetry_LocalStats) isTelemetry_Variant()          {}
func (*Telemetry_HealthMetrics) isTelemetry_Variant()       {}

func (t *Telemetry) GetDeviceMetrics() *DeviceMetrics {
	if x, ok := t.Variant.(*Telemetry_DeviceMetrics); ok {
		return x.DeviceMetrics
	}
	return nil
}

func (t *Telemetry) GetEnvironmentMetrics() *EnvironmentMetrics {
	if x, ok := t.Variant.(*Telemetry_EnvironmentMetrics); ok {
		return x.EnvironmentMetrics
	}
	return nil
}

func (t *Telemetry) GetAirQualityMetrics() *AirQualityMetrics {
	if x, ok := t.Variant.(*Telemetry_AirQualityMetrics); ok {
		return x.AirQualityMetrics
	}
	return nil
}

func (t *Telemetry) GetPowerMetrics() *PowerMetrics {
	if x, ok := t.Variant.(*Telemetry_PowerMetrics); ok {
		return x.PowerMetrics
	}
	return nil
}

func (t *Telemetry) GetLocalStats() *LocalStats {
	if x, ok := t.Variant.(*Telemetry_LocalStats); ok {
		return x.LocalStats
	}
	return nil
}

func (t *Telemetry) GetHealthMetrics() *HealthMetrics {
	if x, ok := t.Variant.(*Telemetry_HealthMetrics); ok {
		return x.HealthMetrics
	}
	return nil
}

func (t *Telemetry) Reset() { *t = Telemetry{} }
func (t *Telemetry) ProtoMessage() {}

// UnmarshalTelemetry decodes a Telemetry message from protobuf wire format.
func UnmarshalTelemetry(buf []byte) (*Telemetry, error) {
	t := &Telemetry{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // time
			if wireType == WireFixed32 {
				if offset+4 > len(buf) {
					return nil, ErrInvalidData
				}
				t.Time = uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
				offset += 4
			} else {
				v, vn := DecodeVarint(buf[offset:])
				if vn == 0 {
					return nil, ErrInvalidData
				}
				t.Time = uint32(v)
				offset += vn
			}

		case 2: // device_metrics
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			dm, err := unmarshalDeviceMetrics(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			t.Variant = &Telemetry_DeviceMetrics{DeviceMetrics: dm}
			offset += int(length)

		case 3: // environment_metrics
			if wireType != WireBytes {
				return nil, ErrInvalidData
			}
			length, ln := DecodeVarint(buf[offset:])
			if ln == 0 {
				return nil, ErrInvalidData
			}
			offset += ln
			if offset+int(length) > len(buf) {
				return nil, ErrInvalidData
			}
			em, err := unmarshalEnvironmentMetrics(buf[offset : offset+int(length)])
			if err != nil {
				return nil, err
			}
			t.Variant = &Telemetry_EnvironmentMetrics{EnvironmentMetrics: em}
			offset += int(length)

		default:
			// Skip unknown field
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return t, nil
}

func unmarshalDeviceMetrics(buf []byte) (*DeviceMetrics, error) {
	dm := &DeviceMetrics{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // battery_level
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			dm.BatteryLevel = uint32(v)
			offset += vn

		case 2: // voltage
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			bits := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			dm.Voltage = float32frombits(bits)
			offset += 4

		case 3: // channel_utilization
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			bits := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			dm.ChannelUtilization = float32frombits(bits)
			offset += 4

		case 4: // air_util_tx
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			bits := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			dm.AirUtilTx = float32frombits(bits)
			offset += 4

		case 5: // uptime_seconds
			v, vn := DecodeVarint(buf[offset:])
			if vn == 0 {
				return nil, ErrInvalidData
			}
			dm.UptimeSeconds = uint32(v)
			offset += vn

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return dm, nil
}

func unmarshalEnvironmentMetrics(buf []byte) (*EnvironmentMetrics, error) {
	em := &EnvironmentMetrics{}
	offset := 0

	for offset < len(buf) {
		tag, n := DecodeVarint(buf[offset:])
		if n == 0 {
			return nil, ErrInvalidData
		}
		offset += n

		field, wireType := DecodeTag(tag)

		switch field {
		case 1: // temperature
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			bits := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			em.Temperature = float32frombits(bits)
			offset += 4

		case 2: // relative_humidity
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			bits := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			em.RelativeHumidity = float32frombits(bits)
			offset += 4

		case 3: // barometric_pressure
			if wireType != WireFixed32 || offset+4 > len(buf) {
				return nil, ErrInvalidData
			}
			bits := uint32(buf[offset]) | uint32(buf[offset+1])<<8 | uint32(buf[offset+2])<<16 | uint32(buf[offset+3])<<24
			em.BarometricPressure = float32frombits(bits)
			offset += 4

		default:
			offset = skipField(buf, offset, wireType)
			if offset < 0 {
				return nil, ErrInvalidData
			}
		}
	}

	return em, nil
}

// float32frombits converts uint32 bits to float32
func float32frombits(b uint32) float32 {
	return *(*float32)(unsafe.Pointer(&b))
}
